import {
  Piece,
  DamageModifiers,
  MaterialType,
  CraftingStation,
  ItemType,
  EntityId,
  mods,
} from '../types';

const damageModifiersElementalPart = {
  fire: 'immune',
  frost: 'immune',
  lightning: 'normal',
  poison: 'immune',
  spirit: 'immune',
} as const;

const damageModifiersFireplace: DamageModifiers = {
  blunt: 'normal',
  slash: 'normal',
  pierce: 'normal',
  chop: 'normal',
  pickaxe: 'normal',
  ...damageModifiersElementalPart,
};

const damageModifieresExtensions: DamageModifiers = mods([0, 0, 1, 2, 0, 0, 1, 0, 3, 3])

const damageModifiersWood: DamageModifiers = {
  blunt: 'normal',
  slash: 'normal',
  pierce: 'resistant',
  chop: 'weak',
  pickaxe: 'normal',
  fire: 'normal',
  frost: 'normal',
  lightning: 'normal',
  poison: 'immune',
  spirit: 'immune',
};

const damageModifiersStone: DamageModifiers = {
  blunt: 'normal',
  slash: 'normal',
  pierce: 'normal',
  chop: 'normal',
  pickaxe: 'weak',
  ...damageModifiersElementalPart,
};

const notOnWood = true;
const onlyOnFlat = true;
const notOnFloor = true;
// const nonRepairable = true;
// const nonRemovable = true;
const allowedInDungeons = true;
const groundOnly = true;

const requiresRoof = true;
const requiresFire = true;
const providesSupport = true;

const wearStructure = (
  hp: number,
  damageModifiers: DamageModifiers,
  materialType: MaterialType | undefined,
  { noRoof = true, noSupport = true }: { noRoof?: boolean, noSupport?: boolean } = {},
) => ({
  hp,
  damageModifiers,
  noRoof,
  noSupport,
  providesSupport: true,
  materialType,
});

const woodResist: DamageModifiers = mods([0, 0, 1, 2, 0, 0, 0, 0, 3, 3]);
const stoneResist: DamageModifiers = mods([0, 0, 0, 0, 2, 1, 1, 0, 3, 3]);
const chestResist: DamageModifiers = mods([1, 1, 1, 1, 1, 1, 1, 0, 3, 3]);
const craftStationResist: DamageModifiers = mods([1, 1, 1, 1, 0, 3, 3, 0, 3, 3]);
const woodStructureWear = wearStructure(400, woodResist, MaterialType.Wood);
const woodRoofStructureWear = { ...woodStructureWear, noRoof: false };
const stoneStructureWear = wearStructure(1500, stoneResist, MaterialType.Stone, { noRoof: false });

const woodStructureRecipe = (wood: number, type: 'Wood' | 'RoundLog' | 'FineWood' = 'Wood') =>
  ({ materials: { [type]: wood }, station: CraftingStation.Workbench, });

const stoneStructureRecipe = (stone: number) =>
  ({ materials: { Stone: stone }, station: CraftingStation.StoneCutter, });

const craftingStationIds = {
//  [CraftingStation.Inventory]: 'Hands'
} as Record<CraftingStation, EntityId>;

export function getCraftingStationId(id: CraftingStation): EntityId {
  return craftingStationIds[id];
}

type StructuralIntegrity = {
  maxSupport: number;
  minSupport: number;
  verticalLoss: number;
  horizontalLoss: number;
};

const durabilityTable: Record<MaterialType, StructuralIntegrity> = {
  [MaterialType.Wood]: {
    maxSupport: 100,
    minSupport: 10,
    verticalLoss: 1/8,
    horizontalLoss: 1/5,
  },
  [MaterialType.Stone]: {
    maxSupport: 1000,
    minSupport: 100,
    verticalLoss: 1/8,
    horizontalLoss: 1,
  },
  [MaterialType.Iron]: {
    maxSupport: 1500,
    minSupport: 20,
    verticalLoss: 1/13,
    horizontalLoss: 1/13,
  },
  [MaterialType.HardWood]: {
    maxSupport: 140,
    minSupport: 10,
    verticalLoss: 1/10,
    horizontalLoss: 1/6,
  },
};

export function getStructuralIntegrity(material: MaterialType): StructuralIntegrity {
  return durabilityTable[material];
}

export const pieces: Piece[] = [
  { id: 'fire_pit',
    type: 'piece',
    subtype: 'fireplace',
    tier: 0,
    piece: { target: 'random', water: false, notOnWood, onlyOnFlat, allowedInDungeons },
    comfort: { value: 1, group: 'fire', },
    fireplace: {
      fuel: 'Wood',
      capacity: 10,
      burnTime: 5000,
      minHeightAbove: 0.5,
      smoke: true,
      fireworks: true,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifiersFireplace,
      noRoof: false,
      noSupport: true,
      providesSupport,
      materialType: MaterialType.Wood,
    },
    recipe: {
      materials: { Wood: 5, Stone: 2 },
      station: CraftingStation.Workbench,
    }
  },
  { id: 'bonfire',
    type: 'piece',
    subtype: 'fireplace',
    tier: 2,
    wear: {
      hp: 300,
      damageModifiers: damageModifiersFireplace,
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    piece: { target: 'random', water: false, notOnWood, onlyOnFlat, },
    comfort: { value: 1, group: 'fire' },
    fireplace: {
      fuel: 'Wood',
      capacity: 10,
      burnTime: 5000,
      minHeightAbove: 1,
      smoke: true,
      fireworks: true,
    },
    recipe: {
      materials: { 
        SurtlingCore: 1,
        ElderBark: 5,
        RoundLog: 5,
        FineWood: 5,
      },
      station: CraftingStation.Workbench,
    }
  },
  { id: 'hearth',
    type: 'piece',
    subtype: 'fireplace',
    tier: 3,
    piece: { target: 'primary', water: false, },
    comfort: { value: 2, group: 'fire' },
    fireplace: {
      fuel: 'Wood',
      capacity: 20,
      burnTime: 5000,
      minHeightAbove: 0.7,
      smoke: true,
      fireworks: false,
    },
    wear: {
      hp: 1500,
      damageModifiers: craftStationResist,
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Stone,
    },
    recipe: stoneStructureRecipe(15),
  },
  { id: 'wood_stack',
    type: 'piece',
    subtype: 'misc',
    tier: 0,
    wear: {
      hp: 50,
      damageModifiers: damageModifiersWood,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    piece: {
      target: 'random',
      water: undefined,
      allowedInDungeons,
    },
    recipe: { materials: { Wood: 15, }, station: CraftingStation.Workbench, }
  },
  { id: 'stone_pile',
    type: 'piece',
    subtype: 'misc',
    tier: 0,
    piece: {
      target: 'random',
      water: undefined,
      allowedInDungeons,
    },
    wear: {
      hp: 50,
      damageModifiers: mods([0, 0, 0, 0, 2, 1, 1, 0, 3, 3]),
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Stone: 50, }, station: CraftingStation.Workbench, }
  },
  { id: 'piece_cookingstation',
    type: 'piece',
    subtype: 'craft',
    tier: 1,
    craft: {
      id: CraftingStation.CookingStation,
      requiresFire,
    },
    piece: {
      target: 'primary',
      water: false,
      allowedInDungeons,
    },
    wear: {
      hp: 20,
      damageModifiers: mods([0, 0, 0, 0, 2, 1, 1, 0, 3, 3]), // TODO: check
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Wood: 2, }, station: CraftingStation.Workbench, }
  },
  { id: 'piece_cauldron',
    type: 'piece',
    subtype: 'craft',
    tier: 2,
    piece: {
      target: 'primary',
      water: false,
    },
    craft: {
      id: CraftingStation.Cauldron,
      requiresFire,
    },
    wear: {
      hp: 100,
      damageModifiers: mods([0, 0, 1, 0, 0, 1, 0, 0, 3, 3]),
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Tin: 10, }, station: CraftingStation.Forge, }
  },
  { id: 'piece_workbench',
    type: 'piece',
    subtype: 'craft',
    tier: 1,
    piece: {
      target: 'primary',
      water: false,
    },
    craft: {
      id: CraftingStation.Workbench,
      requiresRoof,
    },
    wear: {
      hp: 100,
      damageModifiers: mods([0, 0, 1, 0, 0, 1, 0, 0, 3, 3]),
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Wood: 10, }, station: CraftingStation.Inventory, }
  },
  { id: 'piece_workbench_ext1',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 1,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Workbench,
      distance: 5,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Wood: 10, Flint: 10 }, station: CraftingStation.Workbench, }
  },
  { id: 'piece_workbench_ext2',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 1,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Workbench,
      distance: 5,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Wood: 10, Flint: 15, LeatherScraps: 20, DeerHide: 5, }, station: CraftingStation.Workbench, }
  },
  { id: 'piece_workbench_ext3',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 2,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Workbench,
      distance: 5,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { FineWood: 10, Bronze: 3, }, station: CraftingStation.Forge, }
  },
  { id: 'piece_workbench_ext4',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 4,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Workbench,
      distance: 5,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { FineWood: 10, Iron: 4, Obsidian: 4, }, station: CraftingStation.Forge, }
  },
  { id: 'piece_stonecutter',
    type: 'piece',
    subtype: 'craft',
    tier: 3,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    craft: {
      id: CraftingStation.StoneCutter,
      buildRange: 20,
      requiresRoof,
    },
    wear: {
      hp: 200,
      damageModifiers: mods([0, 0, 1, 2, 0, 0, 0, 0, 3, 3]),
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Wood: 10, Iron: 2, Stone: 4 }, station: CraftingStation.Forge, }
  },
  { id: 'piece_artisanstation',
    type: 'piece',
    subtype: 'craft',
    tier: 5,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
    },
    craft: {
      id: CraftingStation.ArtisanTable,
      buildRange: 40,
      requiresRoof,
    },
    wear: {
      hp: 200,
      damageModifiers: mods([0, 0, 1, 2, 0, 0, 0, 0, 3, 3]),
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { FineWood: 10, DragonTear: 2, }, station: CraftingStation.Workbench, }
  },
  { id: 'forge',
    type: 'piece',
    subtype: 'craft',
    tier: 2,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
    },
    craft: {
      id: CraftingStation.Forge,
      buildRange: 20,
      requiresRoof,
    },
    wear: {
      hp: 200,
      damageModifiers: mods([0, 0, 1, 2, 0, 0, 0, 0, 3, 3]),
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Stone: 4, Coal: 4, Wood: 10, Copper: 6 }, station: CraftingStation.Workbench, }
  },
  { id: 'forge_ext1',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 2,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Forge,
      distance: 2,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Wood: 5, DeerHide: 5, Chain: 4 }, station: CraftingStation.Workbench, }
  },
  { id: 'forge_ext2',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 2,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Forge,
      distance: 5,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Wood: 5, Bronze: 2, }, station: CraftingStation.Workbench, }
  },
  { id: 'forge_ext3',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 2,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Forge,
      distance: 5,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Wood: 25, SharpeningStone: 1, }, station: CraftingStation.Workbench, }
  },
  { id: 'forge_ext4',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 3,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Forge,
      distance: 5,
    },
    wear: {
      hp: 1000,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Iron: 20, Wood: 5, }, station: CraftingStation.Workbench, }
  },
  { id: 'forge_ext5',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 3,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Forge,
      distance: 5,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { FineWood: 25, Copper: 10, }, station: CraftingStation.Workbench, }
  },
  { id: 'forge_ext6',
    type: 'piece',
    subtype: 'craft_ext',
    tier: 4,
    piece: {
      target: 'primary',
      water: false,
      notOnFloor,
      requiredSpace: 2,
    },
    extends: {
      id: CraftingStation.Forge,
      distance: 5,
    },
    wear: {
      hp: 100,
      damageModifiers: damageModifieresExtensions,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Wood,
    },
    recipe: { materials: { Iron: 15, Wood: 10, }, station: CraftingStation.Workbench, }
  },
  { id: 'smelter',
    type: 'piece',
    subtype: 'craft',
    tier: 4,
    piece: {
      target: 'primary',
      water: false,
      notOnWood,
      onlyOnFlat,
    },
    craft: { id: CraftingStation.Smelter },
    wear: {
      hp: 2000,
      damageModifiers: craftStationResist,
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Stone,
    },
    recipe: { materials: { Stone: 20, SurtlingCore: 5, }, station: CraftingStation.Workbench, }
  },
  { id: 'blastfurnace',
    type: 'piece',
    subtype: 'craft',
    tier: 5,
    piece: {
      target: 'primary',
      water: false,
      notOnWood,
      onlyOnFlat,
    },
    craft: {
      id: CraftingStation.BlastFurnace,
      queueSize: 10,
    },
    wear: {
      hp: 2000,
      damageModifiers: craftStationResist,
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Stone,
    },
    recipe: { materials: { Stone: 20, SurtlingCore: 5, Iron: 10, FineWood: 20 }, station: CraftingStation.ArtisanTable, }
  },
  { id: 'charcoal_kiln',
    type: 'piece',
    subtype: 'craft',
    tier: 4,
    piece: {
      target: 'primary',
      water: false,
      notOnWood,
      onlyOnFlat,
    },
    craft: { id: CraftingStation.CharcoalKiln, queueSize: 25 },
    wear: {
      hp: 1500,
      damageModifiers: craftStationResist,
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Stone,
    },
    recipe: { materials: { Stone: 20, SurtlingCore: 5, }, station: CraftingStation.Workbench, }
  },
  { id: 'windmill',
    type: 'piece',
    subtype: 'craft',
    tier: 5,
    piece: {
      target: 'primary',
      water: false,
      notOnWood,
      onlyOnFlat,
    },
    craft: { id: CraftingStation.Windmill, queueSize: 50 },
    wear: {
      hp: 1000,
      damageModifiers: craftStationResist,
      noRoof: false,
      noSupport: true,
      materialType: MaterialType.Stone,
    },
    recipe: { materials: { Stone: 20, Wood: 30, IronNails: 30 }, station: CraftingStation.ArtisanTable, }
  },
  { id: 'piece_spinningwheel',
    type: 'piece',
    subtype: 'craft',
    tier: 5,
    piece: {
      target: 'primary',
      water: false,
      onlyOnFlat,
    },
    craft: { id: CraftingStation.SpinningWheel, queueSize: 40, requiresRoof, },
    wear: {
      hp: 200,
      damageModifiers: craftStationResist,
      noRoof: true,
      noSupport: true,
      materialType: MaterialType.Stone,
    },
    recipe: { materials: { FineWood: 20, IronNails: 10, LeatherScraps: 5 }, station: CraftingStation.ArtisanTable, }
  },
  // walls / floors
  { id: 'wood_floor',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'none', water: undefined, size: [2, 2, 0] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_floor_1x1',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'none', water: undefined, size: [1, 1, 0] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(1),
  },
  { id: 'woodwall',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 2] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'woodwall_half',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 1] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(1),
  },
  { id: 'wood_door',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 2] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(4),
  },
  { id: 'wood_gate',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 3] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(12),
  },
  { id: 'wood_stair',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'none', water: undefined, size: [2, 3, 1] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_stepladder',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'none', water: undefined, size: [2, 3, 1] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_roof_45',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 2, 1] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_roof_top_45',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 2, 1] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_roof_ocorner_45',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 2, 1] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_roof_icorner_45',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 2, 1] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_wall_roof_45',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 2] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_wall_roof_top_45',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 1] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_roof',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 2] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_roof_top',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 2, 1] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_roof_ocorner',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 2, 1] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_roof_icorner',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 2, 1] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_wall_roof',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 1] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_wall_roof_top',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 1] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_pole',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [0, 0, 1] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(1),
  },
  { id: 'wood_pole2',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [0, 0, 2] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_beam1',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [1, 0, 0] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(1),
  },
  { id: 'wood_beam',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 0] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_beam_26',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 1] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'wood_beam_45',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 1] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'woodiron_pole',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [2, 0, 1] },
    wear: wearStructure(2000, woodResist, MaterialType.Iron),
    recipe: { materials: { Wood: 2, Iron: 1 }, station: CraftingStation.Forge, },
  },
  { id: 'woodiron_beam',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [2, 0, 1] },
    wear: wearStructure(2000, woodResist, MaterialType.Iron),
    recipe: { materials: { Wood: 2, Iron: 1 }, station: CraftingStation.Forge, },
  },
  { id: 'wood_dragon',
    type: 'piece',
    subtype: 'structure',
    tier: 2,
    piece: { target: 'random', water: undefined, size: [3, 0, 2] },
    wear: woodRoofStructureWear,
    recipe: woodStructureRecipe(10, 'FineWood'),
  },
  { id: 'wood_wall_log_4x0.5',
    type: 'piece',
    subtype: 'structure',
    tier: 2,
    piece: { target: 'random', water: undefined, size: [4, 0.5, 0.5] },
    wear: wearStructure(500, woodResist, MaterialType.HardWood),
    recipe: woodStructureRecipe(2, 'RoundLog'),
  },
  { id: 'wood_wall_log',
    type: 'piece',
    subtype: 'structure',
    tier: 2,
    piece: { target: 'random', water: undefined, size: [2, 0.5, 0.5] },
    wear: wearStructure(500, woodResist, MaterialType.HardWood),
    recipe: woodStructureRecipe(1, 'RoundLog'),
  },
  { id: 'wood_pole_log',
    type: 'piece',
    subtype: 'structure',
    tier: 2,
    piece: { target: 'random', water: undefined, size: [0.5, 0.5, 2] },
    wear: wearStructure(500, woodResist, MaterialType.HardWood),
    recipe: woodStructureRecipe(1, 'RoundLog'),
  },
  { id: 'wood_pole_log_4',
    type: 'piece',
    subtype: 'structure',
    tier: 2,
    piece: { target: 'random', water: undefined, size: [0.5, 0.5, 2] },
    wear: wearStructure(500, woodResist, MaterialType.HardWood),
    recipe: woodStructureRecipe(2, 'RoundLog'),
  },
  { id: 'wood_fence',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 2] },
    wear: woodStructureWear,
    recipe: woodStructureRecipe(2),
  },
  { id: 'stake_wall',
    type: 'piece',
    subtype: 'structure',
    tier: 1,
    piece: { target: 'random', water: undefined, size: [2, 0, 3] },
    wear: wearStructure(1000, woodResist, MaterialType.Wood, { noRoof: false }),
    recipe: woodStructureRecipe(2),
  },
  { id: 'piece_sharpstakes',
    type: 'piece',
    subtype: 'structure',
    tier: 2,
    piece: { target: 'random', water: undefined, groundOnly, size: [3, 0, 1] },
    wear: wearStructure(200, woodResist, MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { Wood: 6, RoundLog: 4 }, station: CraftingStation.Workbench, },
  },
  { id: 'stone_wall_1x1',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [1, 1, 1] },
    wear: stoneStructureWear,
    recipe: stoneStructureRecipe(3),
  },
  { id: 'stone_wall_2x1',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [2, 1, 1] },
    wear: stoneStructureWear,
    recipe: stoneStructureRecipe(4),
  },
  { id: 'stone_wall_4x2',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [4, 1, 2] },
    wear: stoneStructureWear,
    recipe: stoneStructureRecipe(6),
  },
  { id: 'stone_pillar',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [1, 1, 2] },
    wear: stoneStructureWear,
    recipe: stoneStructureRecipe(5),
  },
  { id: 'stone_arch',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [2, 1, 1] },
    wear: stoneStructureWear,
    recipe: stoneStructureRecipe(4),
  },
  { id: 'stone_floor_2x2',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [2, 2, 1] },
    wear: stoneStructureWear,
    recipe: stoneStructureRecipe(6),
  },
  { id: 'iron_gate',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [2, 0, 3] },
    wear: wearStructure(2000, mods([0, 0, 0, 0, 0, 0, 0, 0, 3, 3]), MaterialType.Iron),
    recipe: { materials: { Iron: 4 }, station: CraftingStation.Forge },
  },
  { id: 'stone_stair',
    type: 'piece',
    subtype: 'structure',
    tier: 3,
    piece: { target: 'random', water: undefined, size: [2, 2, 1] },
    wear: stoneStructureWear,
    recipe: stoneStructureRecipe(8),
  },
  { id: 'bed',
    type: 'piece',
    subtype: 'bed',
    tier: 1,
    piece: { target: 'primary', water: false, onlyOnFlat, size: [2, 1, 0.5] },
    comfort: { value: 1, group: 'bed' },
    wear: wearStructure(100, woodResist, MaterialType.Wood),
    recipe: woodStructureRecipe(8),
  },
  { id: 'piece_bed02',
    type: 'piece',
    subtype: 'bed',
    tier: 4,
    piece: { target: 'primary', water: false, onlyOnFlat, size: [2, 2, 2] },
    comfort: { value: 2, group: 'bed' },
    wear: wearStructure(300, woodResist, MaterialType.Wood),
    recipe: {
      materials: { FineWood: 40, DeerHide: 7, WolfPelt: 4, Feathers: 10, IronNails: 15 },
      station: CraftingStation.Workbench,
    },
  },
  { id: 'piece_chest_wood',
    type: 'piece',
    subtype: 'chest',
    tier: 1,
    space: [5, 2],
    piece: { target: 'primary', water: false, onlyOnFlat, size: [2, 1, 1] },
    wear: wearStructure(100, chestResist, MaterialType.Wood, { noRoof: false }),
    recipe: woodStructureRecipe(10),
  },
  { id: 'piece_chest',
    type: 'piece',
    subtype: 'chest',
    tier: 3,
    space: [6, 4],
    piece: { target: 'primary', water: false, onlyOnFlat, size: [2, 1, 1] },
    wear: wearStructure(1000, chestResist, MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { FineWood: 10, Iron: 2 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_chest_private',
    type: 'piece',
    subtype: 'chest',
    tier: 3,
    space: [3, 2],
    piece: { target: 'primary', water: false, onlyOnFlat, size: [1, 0.5, 0.5] },
    wear: wearStructure(10000, chestResist, MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { FineWood: 10, Iron: 8 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_chair',
    type: 'piece',
    subtype: 'chair',
    tier: 2,
    comfort: { value: 1, group: 'sit' },
    piece: { target: 'random', water: false, onlyOnFlat, size: [0.5, 0.5, 0.5] },
    wear: wearStructure(100, woodResist, MaterialType.Wood),
    recipe: woodStructureRecipe(4, 'FineWood'),
  },
  { id: 'piece_chair2',
    type: 'piece',
    subtype: 'chair',
    tier: 2,
    comfort: { value: 2, group: 'sit' },
    piece: { target: 'random', water: false, onlyOnFlat, size: [0.5, 0.5, 1] },
    wear: wearStructure(100, woodResist, MaterialType.Wood),
    recipe: woodStructureRecipe(4, 'FineWood'),
  },
  { id: 'piece_bench01',
    type: 'piece',
    subtype: 'chair',
    tier: 2,
    comfort: { value: 1, group: 'sit' },
    piece: { target: 'random', water: false, onlyOnFlat, size: [2, 0.5, 0.5] },
    wear: wearStructure(100, woodResist, MaterialType.Wood),
    recipe: woodStructureRecipe(4, 'FineWood'),
  },
  { id: 'piece_throne01',
    type: 'piece',
    subtype: 'chair',
    tier: 3,
    comfort: { value: 3, group: 'sit' },
    piece: { target: 'random', water: false, onlyOnFlat, size: [1, 1, 1.5] },
    wear: wearStructure(250, woodResist, MaterialType.Wood),
    recipe: { materials: { FineWood: 20, IronNails: 10 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_table',
    type: 'piece',
    subtype: 'table',
    tier: 2,
    comfort: { value: 1 },
    piece: { target: 'random', water: false, onlyOnFlat, size: [3, 2, 0.5] },
    wear: wearStructure(100, woodResist, MaterialType.Wood),
    recipe: woodStructureRecipe(6, 'FineWood'),
  },
  { id: 'piece_walltorch',
    type: 'piece',
    subtype: 'fireplace',
    tier: 3,
    fireplace: { fuel: 'Resin', capacity: 6, burnTime: 20000, minHeightAbove: 0.68, smoke: false, fireworks: false },
    piece: { target: 'primary', water: undefined, onlyOnFlat, size: [0, 0, 1.5] },
    wear: wearStructure(100, mods([2, 0, 0, 0, 0, 0, 0, 0, 3, 3]), undefined, { noRoof: false }),
    recipe: { materials: { Wood: 2, Copper: 2, Resin: 2 }, station: CraftingStation.Forge },
  },
  { id: 'piece_groundtorch',
    type: 'piece',
    subtype: 'fireplace',
    tier: 3,
    fireplace: { fuel: 'Resin', capacity: 6, burnTime: 20000, minHeightAbove: 0.76, smoke: false, fireworks: false },
    piece: { target: 'primary', water: undefined, onlyOnFlat, size: [0, 0, 1.5] },
    wear: wearStructure(200, mods([0, 0, 1, 0, 0, 3, 3, 0, 3, 3]), undefined, { noRoof: false }),
    recipe: { materials: { Iron: 2, Resin: 2 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_groundtorch_wood',
    type: 'piece',
    subtype: 'fireplace',
    tier: 1,
    fireplace: { fuel: 'Resin', capacity: 4, burnTime: 10000, minHeightAbove: 0.76, smoke: false, fireworks: false },
    piece: { target: 'primary', water: undefined, onlyOnFlat, size: [0, 0, 1.5] },
    wear: wearStructure(100, mods([0, 2, 1, 2, 0, 0, 0, 0, 3, 3]), undefined, { noRoof: false }),
    recipe: { materials: { Iron: 2, Resin: 2 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_groundtorch_green',
    type: 'piece',
    subtype: 'fireplace',
    tier: 3,
    fireplace: { fuel: 'Guck', capacity: 6, burnTime: 20000, minHeightAbove: 0.76, smoke: false, fireworks: false },
    piece: { target: 'primary', water: undefined, onlyOnFlat, size: [0, 0, 1.5] },
    wear: wearStructure(200, mods([0, 0, 1, 0, 0, 3, 3, 0, 3, 3]), undefined, { noRoof: false }),
    recipe: { materials: { Iron: 2, Resin: 2 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_brazierceiling01',
    type: 'piece',
    subtype: 'fireplace',
    tier: 3,
    fireplace: { fuel: 'Coal', capacity: 5, burnTime: 20000, minHeightAbove: 0.28, smoke: false, fireworks: false },
    comfort: { value: 1, group: 'fire' },
    piece: { target: 'random', water: false, onlyOnFlat, size: [0, 0, 1.5] },
    wear: wearStructure(100, mods([0, 0, 0, 0, 0, 3, 3, 0, 3, 3]), MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { Bronze: 5, Coal: 2, Chain: 1 }, station: CraftingStation.Forge },
  },
  { id: 'portal_wood',
    type: 'piece',
    subtype: 'misc',
    tier: 2,
    piece: { target: 'primary', water: false, onlyOnFlat, size: [3, 3, 0] },
    wear: wearStructure(400, mods([1, 0, 1, 2, 1, 0, 0, 0, 3, 3]), MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { GreydwarfEye: 10, FineWood: 20, SurtlingCore: 2 }, station: CraftingStation.Workbench },
  },
  { id: 'guard_stone',
    type: 'piece',
    subtype: 'misc',
    tier: 2,
    piece: { target: 'primary', water: false, onlyOnFlat, size: [0.5, 0.5, 1] },
    wear: wearStructure(1000, mods([0, 0, 1, 4, 4, 0, 1, 0, 3, 3]), undefined, { noRoof: false }),
    recipe: { materials: { FineWood: 5, GreydwarfEye: 5, SurtlingCore: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'itemstand',
    type: 'piece',
    subtype: 'stand',
    supportedTypes: [
      ItemType.OneHandedWeapon,
      ItemType.TwoHandedWeapon,
      ItemType.Bow,
      ItemType.Tool,
      ItemType.Shield,
      ItemType.Helmet,
      ItemType.Trophie,
      ItemType.Misc,
      ItemType.Consumable,
    ], // ['weapon', 'tool', 'shield', 'armor/head', 'trophy', 'resource', 'food', 'potion']
    tier: 2,
    piece: { target: 'none', water: false, onlyOnFlat, size: [0.25, 0.25, 0] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { FineWood: 4, BronzeNails: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'itemstandh',
    type: 'piece',
    subtype: 'stand',
    supportedTypes: [
      ItemType.OneHandedWeapon,
      ItemType.TwoHandedWeapon,
      ItemType.Bow,
      ItemType.Tool,
      ItemType.Shield,
      ItemType.Helmet,
      ItemType.Trophie,
      ItemType.Misc,
    ], // -MeadTasty
    // ['weapon', 'tool', 'shield', 'armor/head', 'trophy', 'resource']
    tier: 2,
    piece: { target: 'none', water: undefined, size: [0.25, 0, 0.25] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { FineWood: 4, BronzeNails: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'sign',
    type: 'piece',
    subtype: 'misc',
    tier: 2,
    piece: { target: 'none', water: undefined, size: [0.25, 0.1, 0] },
    wear: { ...woodRoofStructureWear, hp: 100 },
    recipe: { materials: { FineWood: 4, BronzeNails: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'rug_fur', // lox
    type: 'piece',
    subtype: 'decoration',
    tier: 5,
    comfort: { value: 1 },
    piece: { target: 'none', water: undefined, onlyOnFlat, size: [0.25, 0, 1] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { LoxPelt: 4 }, station: CraftingStation.Workbench },
  },
  { id: 'rug_wolf',
    type: 'piece',
    subtype: 'decoration',
    tier: 4,
    comfort: { value: 1 },
    piece: { target: 'none', water: undefined, onlyOnFlat, size: [2, 1.5, 0] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { WolfPelt: 4 }, station: CraftingStation.Workbench },
  },
  { id: 'rug_deer',
    type: 'piece',
    subtype: 'decoration',
    tier: 1,
    comfort: { value: 1 },
    piece: { target: 'none', water: undefined, onlyOnFlat, size: [2, 1.5, 0] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { WolfPelt: 4 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_banner01',
    type: 'piece',
    subtype: 'decoration',
    tier: 2,
    comfort: { value: 1, group: 'banner' },
    piece: { target: 'none', water: undefined, size: [1, 2, 0] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { FineWood: 2, LeatherScraps: 6, Coal: 4 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_banner02',
    type: 'piece',
    subtype: 'decoration',
    tier: 2,
    comfort: { value: 1, group: 'banner' },
    piece: { target: 'none', water: undefined, size: [1, 2, 0] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { FineWood: 2, LeatherScraps: 6, Blueberries: 4 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_banner03',
    type: 'piece',
    subtype: 'decoration',
    tier: 2,
    comfort: { value: 1, group: 'banner' },
    piece: { target: 'none', water: undefined, size: [1, 2, 0] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { FineWood: 2, LeatherScraps: 6, Raspberry: 4 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_banner04',
    type: 'piece',
    subtype: 'decoration',
    tier: 3,
    comfort: { value: 1, group: 'banner' },
    piece: { target: 'none', water: undefined, size: [1, 2, 0] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { FineWood: 2, LeatherScraps: 6, Bloodbag: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_banner05',
    type: 'piece',
    subtype: 'decoration',
    tier: 3,
    comfort: { value: 1, group: 'banner' },
    piece: { target: 'none', water: undefined, size: [1, 2, 0] },
    wear: { ...woodRoofStructureWear, hp: 50 },
    recipe: { materials: { FineWood: 2, LeatherScraps: 6, Guck: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_beehive',
    type: 'piece',
    subtype: 'craft',
    tier: 1,
    craft: { id: CraftingStation.BeeHive },
    piece: { target: 'primary', water: undefined, size: [0.5, 0.5, 0.5] },
    wear: { ...woodRoofStructureWear, hp: 100 },
    recipe: { materials: { Wood: 10, QueenBee: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'fermenter',
    type: 'piece',
    subtype: 'craft',
    tier: 2,
    craft: { id: CraftingStation.Fermenter, requiresRoof },
    piece: { target: 'primary', water: false, onlyOnFlat, size: [2, 2, 3] },
    wear: wearStructure(1000, craftStationResist, MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { FineWood: 30, Bronze: 5, Resin: 10 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_gift1', disabled: true,
    type: 'piece',
    subtype: 'chest',
    tier: 1,
    space: [1, 1],
    piece: { target: 'none', water: false, onlyOnFlat, size: [0.5, 0.5, 0.5] },
    wear: wearStructure(10, mods([1, 1, 1, 1, 1, 1, 1, 0, 3, 3]), MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { FineWood: 2, BoneFragments: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_gift2', disabled: true,
    type: 'piece',
    subtype: 'chest',
    tier: 1,
    space: [1, 1],
    piece: { target: 'none', water: false, onlyOnFlat, size: [0.5, 0.5, 0.5] },
    wear: wearStructure(10, mods([1, 1, 1, 1, 1, 1, 1, 0, 3, 3]), MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { FineWood: 2, BoneFragments: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_gift3', disabled: true,
    type: 'piece',
    subtype: 'chest',
    tier: 1,
    space: [1, 1],
    piece: { target: 'none', water: false, onlyOnFlat, size: [0.5, 0.5, 0.5] },
    wear: wearStructure(10, mods([1, 1, 1, 1, 1, 1, 1, 0, 3, 3]), MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { FineWood: 2, BoneFragments: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_xmastree', disabled: true,
    type: 'piece',
    tier: 1,
    subtype: 'decoration',
    comfort: { value: 1 },
    piece: { target: 'random', water: undefined, size: [1, 1, 2] },
    wear: wearStructure(50, woodResist, MaterialType.Wood, { noRoof: false }),
    recipe: { materials: { Wood: 10, FirCone: 1 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_maypole', disabled: true,
    type: 'piece',
    tier: 1,
    subtype: 'decoration',
    comfort: { value: 1 },
    piece: { target: 'random', water: undefined, size: [2, 1, 3] },
    wear: wearStructure(50, woodResist, undefined, { noRoof: false }),
    recipe: { materials: { Wood: 10, Dandelion: 4, Thistle: 4 }, station: CraftingStation.Workbench },
  },
  { id: 'piece_jackoturnip', disabled: true,
    type: 'piece',
    subtype: 'fireplace',
    tier: 1,
    fireplace: { fuel: 'Resin', capacity: 6, burnTime: 20000, minHeightAbove: 0.76, smoke: false, fireworks: false },
    piece: { target: 'primary', water: undefined, size: [0.5, 0.5, 0.5] },
    wear: wearStructure(200, mods([0, 0, 1, 0, 0, 3, 3, 0, 3, 3]), undefined, { noRoof: false }),
    recipe: { materials: { Turnip: 4, Resin: 2 }, station: CraftingStation.Workbench },
  },
];

pieces.forEach(p => {
  if (p.subtype === 'craft') {
    craftingStationIds[p.craft.id] = p.id;
  }
});

