export const plants = [
  {
    id: "Beech",
    growTime: [3000, 5000],
    cultivatedGround: false,
    destroyUnhealthy: true,
    freeSpaceRadius: 2,
    biomes: ['Meadows', 'BlackForest', 'Plains'],
  },
  {
    id: "PineTree",
    growTime: [3000, 5000],
    cultivatedGround: false,
    destroyUnhealthy: true,
    freeSpaceRadius: 2,
    biomes: ['Meadows', 'BlackForest', 'Plains'],
  },
  {
    id: "FirTree",
    growTime: [3000, 5000],
    cultivatedGround: false,
    destroyUnhealthy: true,
    freeSpaceRadius: 2,
    biomes: ['Meadows', 'BlackForest', 'Mountain', 'Plains'],
  },
  {
    id: "Turnip",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: ['Meadows', 'BlackForest', 'Swamp', 'Plains'],
  },
  {
    id: "Barley",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: ['Plains'],
  },
  {
    id: "Carrot",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: ['Meadows', 'BlackForest', 'Plains'],
  },
  {
    id: "SeedCarrot",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: ['Meadows', 'BlackForest', 'Plains'],
  },
  {
    id: "Flax",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: ['Plains'],
  },
  {
    id: "SeedTurnip",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: ['Meadows', 'BlackForest', 'Swamp', 'Plains'],
  },
] as const;
