import { Biome } from "../types";

export const plants = [
  {
    id: "Beech",
    growTime: [3000, 5000],
    cultivatedGround: false,
    destroyUnhealthy: true,
    freeSpaceRadius: 2,
    biomes: [Biome.Meadows, Biome.BlackForest, Biome.Plains],
  },
  {
    id: "PineTree",
    growTime: [3000, 5000],
    cultivatedGround: false,
    destroyUnhealthy: true,
    freeSpaceRadius: 2,
    biomes: [Biome.Meadows, Biome.BlackForest, Biome.Plains],
  },
  {
    id: "FirTree",
    growTime: [3000, 5000],
    cultivatedGround: false,
    destroyUnhealthy: true,
    freeSpaceRadius: 2,
    biomes: [Biome.Meadows, Biome.BlackForest, Biome.Mountain, Biome.Plains],
  },
  {
    id: "Turnip",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: [Biome.Meadows, Biome.BlackForest, Biome.Swamp, Biome.Plains],
  },
  {
    id: "Barley",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: [Biome.Plains],
  },
  {
    id: "Carrot",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: [Biome.Meadows, Biome.BlackForest, Biome.Plains],
  },
  {
    id: "SeedCarrot",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: [Biome.Meadows, Biome.BlackForest, Biome.Plains],
  },
  {
    id: "Flax",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: [Biome.Plains],
  },
  {
    id: "SeedTurnip",
    growTime: [4000, 5000],
    cultivatedGround: true,
    destroyUnhealthy: true,
    freeSpaceRadius: 0.5,
    biomes: [Biome.Meadows, Biome.BlackForest, Biome.Swamp, Biome.Plains],
  },
] as const;
