import { Item, CraftingStation } from "../types";

const CAULDRON_TIME = 3;
const FORGE_TIME = 2;
// artisan table = 1
// workbench = 1
const KILN_TIME = 15;
const SMELTER_TIME = 30;
const FURNACE_TIME = 30;
const SPIN_WHEEL_TIME = 30;
const FERMENT_TIME = 2400;

export const resources: Item[] = [
// MEADOWS
  { type: 'item', id: 'Wood', weight: 2, stack: 50 },
  { type: 'item', id: 'Coal', weight: 2, stack: 50,
    recipe: { time: KILN_TIME, materials: { wood: 1 },
              source: { station: CraftingStation.CharcoalKiln }, number: 1 } },
  { type: 'item', id: 'Resin', weight: 0.3, stack: 50 },
  { type: 'item', id: 'Feathers', weight: 0.1, stack: 50 },
  { type: 'item', id: 'Stone', weight: 2, stack: 50 },
  { type: 'item', id: 'Flint', weight: 2, stack: 30 },
  { type: 'item', id: 'LeatherScraps', weight: 0.5, stack: 50 },
  { type: 'item', id: 'DeerHide', weight: 1, stack: 50 },
  { type: 'item', id: 'QueenBee', weight: 0.2, stack: 20 },
  { type: 'food', id: 'Raspberry', weight: 0.1, stack: 50,
    health: 10, stamina: 20, duration: 600, regen: 1 },
  { type: 'food', id: 'Mushroom', weight: 0.1, stack: 50,
    health: 15, stamina: 20, duration: 600, regen: 1 },
  { type: 'item', id: 'Dandelion', weight: 0.1, stack: 50 },
  { type: 'food', id: 'Honey', weight: 0.2, stack: 50,
    health: 20, stamina: 20, duration: 300, regen: 5 },
  { type: 'item', id: 'RawMeat', weight: 1, stack: 20 },
  { type: 'food', id: 'CookedMeat', weight: 1, stack: 20,
    health: 40, stamina: 30, duration: 1200, regen: 2,
    recipe: { time: 25, materials: { RawMeat: 1 },
              source: { station: CraftingStation.CookingStation }, number: 1 } },
  { type: 'item', id: 'NeckTail', weight: 0.5, stack: 50 },
  { type: 'food', id: 'NeckTailGrilled', weight: 0.5, stack: 50,
    health: 35, stamina: 20, duration: 1000, regen: 2,
    recipe: { time: 20, materials: { NeckTail: 1 },
              source: { station: CraftingStation.CookingStation }, number: 1 } },
  { type: 'item', id: 'TrophyBoar', weight: 2, stack: 50 },
  { type: 'item', id: 'TrophyDeer', weight: 2, stack: 50 },
  { type: 'item', id: 'TrophyNeck', weight: 0.5, stack: 50 },
  { type: 'item', id: 'TrophyGreyling', weight: 1, stack: 20 },
  { type: 'item', id: 'TrophyEikthyr', weight: 2, stack: 20 },
  { type: 'item', id: 'HardAntler', weight: 2, stack: 50 },
// BLACK FOREST
  { type: 'item', id: 'FineWood', weight: 2, stack: 50 },
  { type: 'item', id: 'GreydwarfEye', weight: 0.2, stack: 50 },
  { type: 'item', id: 'BoneFragments', weight: 0.5, stack: 50 },
  { type: 'item', id: 'SurtlingCore', weight: 5, stack: 10 },
  { type: 'item', id: 'AncientSeed', weight: 1, stack: 50 },
  { type: 'item', id: 'RoundLog', weight: 2, stack: 50 },
  { type: 'item', id: 'TrollHide', weight: 2, stack: 20 },
  { type: 'item', id: 'CopperOre', weight: 10, stack: 30, teleportable: false },
  { type: 'item', id: 'Copper', weight: 10, stack: 30, teleportable: false,
    recipe: { time: SMELTER_TIME, materials: { CopperOre: 1, Coal: 2 },
              source: { station: CraftingStation.Smelter }, number: 1 } },
  { type: 'item', id: 'TinOre', weight: 8, stack: 30, teleportable: false },
  { type: 'item', id: 'Tin', weight: 8, stack: 30, teleportable: false,
    recipe: { time: SMELTER_TIME, materials: { TinOre: 1, Coal: 2 },
              source: { station: CraftingStation.Smelter }, number: 1 } },
  { type: 'item', id: 'Bronze', weight: 12, stack: 30, teleportable: false,
    recipe: { time: FORGE_TIME, materials: { Copper: 2, Tin: 1 },
              source: { station: CraftingStation.Smelter }, number: 1 } },
  { type: 'item', id: 'BronzeNails', weight: 0.5, stack: 100, teleportable: false,
    recipe: { time: FORGE_TIME, materials: { Bronze: 1 },
              source: { station: CraftingStation.Forge }, number: 20 } },
  { type: 'value', id: 'Coins', weight: 0.1, stack: 999, value: 1 },
  { type: 'value', id: 'Ruby', weight: 0.1, stack: 20, value: 20 },
  { type: 'value', id: 'Amber', weight: 0.1, stack: 20, value: 5 },
  { type: 'value', id: 'AmberPearl', weight: 0.1, stack: 50, value: 10 },
  { type: 'value', id: 'SilverNecklace', weight: 0.1, stack: 50, value: 30 },
  { type: 'item', id: 'YmirRemains', weight: 0.3, stack: 50, recipe: { value: 120 } },
  { type: 'item', id: 'CarrotSeeds', weight: 0.1, stack: 100 },
  { type: 'food', id: 'Blueberries', weight: 0.1, stack: 50,
    health: 15, stamina: 20, duration: 600, regen: 1 },
  { type: 'food', id: 'QueensJam', weight: 0.1, stack: 50,
    health: 15, stamina: 20, duration: 600, regen: 1,
    recipe: { time: CAULDRON_TIME, materials: { Raspberry: 8, Blueberries: 8 },
              source: { station: CraftingStation.Cauldron }, number: 4 } },
  { type: 'food', id: 'MushroomYellow', weight: 0.1, stack: 50,
    health: 20, stamina: 20, duration: 600, regen: 1 },
  { type: 'item', id: 'Thistle', weight: 0.1, stack: 50 },
  { type: 'food', id: 'Carrot', weight: 0.3, stack: 50,
    health: 15, stamina: 15, duration: 600, regen: 1 },
  { type: 'food', id: 'CarrotSoup', weight: 1, stack: 10,
    health: 20, stamina: 60, duration: 1500, regen: 2,
    recipe: { time: CAULDRON_TIME, materials: { Mushroom: 1, Carrot: 3 },
              source: { station: CraftingStation.Cauldron }, number: 1 } },
  { type: 'item', id: 'TrophySkeleton', weight: 0.5, stack: 20 },
  { type: 'item', id: 'TrophySkeletonPoison', weight: 0.5, stack: 20 },
  { type: 'item', id: 'TrophyGreydwarf', weight: 1, stack: 20 },
  { type: 'item', id: 'TrophyGreydwarfBrute', weight: 1.5, stack: 20 },
  { type: 'item', id: 'TrophyGreydwarfShaman', weight: 1, stack: 20 },
  { type: 'item', id: 'TrophyFrostTroll', weight: 4, stack: 20 },
// SWAMP
  { type: 'item', id: 'Ooze', weight: 0.5, stack: 50 },
  { type: 'item', id: 'Guck', weight: 0.5, stack: 50 },
  { type: 'item', id: 'Chain', weight: 2, stack: 50 },
  { type: 'item', id: 'Bloodbag', weight: 0.5, stack: 50 },
  { type: 'item', id: 'Turnip', weight: 0.3, stack: 50 },
  { type: 'item', id: 'TurnipSeeds', weight: 0.1, stack: 100 },
  { type: 'food', id: 'TurnipStew', weight: 1, stack: 10,
    health: 50, stamina: 50, duration: 1600, regen: 2,
    recipe: { time: CAULDRON_TIME, materials: { RawMeat: 1, Turnip: 3 },
              source: { station: CraftingStation.Cauldron }, number: 1 } },
  { type: 'item', id: 'Entrails', weight: 0.3, stack: 50 },
  { type: 'food', id: 'Sausages', weight: 0.5, stack: 20,
    health: 60, stamina: 40, duration: 1600, regen: 3,
    recipe: { time: CAULDRON_TIME, materials: { Entrails: 2, RawMeat: 1, Thistle: 4 },
              source: { station: CraftingStation.Cauldron }, number: 4 } },
  { type: 'item', id: 'ElderBark', weight: 2, stack: 50 },
  { type: 'item', id: 'IronScrap', weight: 10, stack: 30, teleportable: false },
  { type: 'item', id: 'Iron', weight: 12, stack: 30, teleportable: false,
    recipe: { time: SMELTER_TIME, materials: { IronScrap: 1, Coal: 2 },
              source: { station: CraftingStation.Smelter }, number: 1 } },
  { type: 'item', id: 'IronNails', weight: 0.5, stack: 100, teleportable: false,
    recipe: { time: FORGE_TIME, materials: { Iron: 1 },
              source: { station: CraftingStation.Forge }, number: 10 } },
  { type: 'item', id: 'WitheredBone', weight: 1, stack: 30 },
  { type: 'item', id: 'TrophyLeech', weight: 2, stack: 20 },
  { type: 'item', id: 'TrophyBlob', weight: 2, stack: 20 },
  { type: 'item', id: 'TrophyDraugr', weight: 2, stack: 20 },
  { type: 'item', id: 'TrophyDraugrElite', weight: 2, stack: 20 },
  { type: 'item', id: 'TrophyBonemass', weight: 2, stack: 20 },
  { type: 'item', id: 'Wishbone', weight: 0.1, stack: 1 },
// OCEAN
  { type: 'item', id: 'Chitin', weight: 2, stack: 50 },
  { type: 'item', id: 'SerpentScale', weight: 2, stack: 50 },
  { type: 'item', id: 'SerpentMeat', weight: 10, stack: 50 },
  { type: 'food', id: 'SerpentMeatCooked', weight: 1, stack: 10,
    health: 70, stamina: 40, duration: 2000, regen: 3,
    recipe: { time: 60, materials: { SerpentMeat: 1 },
              source: { station: CraftingStation.CookingStation }, number: 1 } },
  { type: 'food', id: 'SerpentStew', weight: 1, stack: 10,
    health: 80, stamina: 80, duration: 2400, regen: 4,
    recipe: { time: CAULDRON_TIME, materials: { Mushroom: 1, CookedSerpentMeat: 1, Honey: 2 },
              source: { station: CraftingStation.Cauldron }, number: 1 } },
  { type: 'item', id: 'TrophySerpent', weight: 25, stack: 20 },
// MOUNTAIN
  { type: 'item', id: 'WolfPelt', weight: 1, stack: 50 },
  { type: 'item', id: 'WolfFang', weight: 0.1, stack: 50 },
  { type: 'item', id: 'FreezeGland', weight: 0.5, stack: 50 },
  { type: 'item', id: 'SilverOre', weight: 14, stack: 30, teleportable: false },
  { type: 'item', id: 'Silver', weight: 14, stack: 30, teleportable: false,
    recipe: { time: SMELTER_TIME, materials: { SilverOre: 1, Coal: 2 },
              source: { station: CraftingStation.Smelter }, number: 1 } },
  { type: 'item', id: 'Obsidian', weight: 2, stack: 50 },
  { type: 'item', id: 'Crystal', weight: 8, stack: 50 },
  { type: 'item', id: 'DragonEgg', weight: 200, stack: 1, teleportable: false },
  { type: 'item', id: 'DragonTear', weight: 1, stack: 50 },
  { type: 'item', id: 'TrophyWolf', weight: 1.5, stack: 20 },
  { type: 'item', id: 'TrophyFenring', weight: 2, stack: 20 },
  { type: 'item', id: 'TrophyDrake', weight: 2, stack: 20 },
  { type: 'item', id: 'TrophySGolem', weight: 2, stack: 20 },
// PLAINS
  { type: 'item', id: 'Flax', weight: 0.2, stack: 100,
    recipe: { time: 4500, materials: { Flax: 1 },
              source: { station: CraftingStation.Cultivator }, number: 2 } },
  { type: 'item', id: 'LinenThread', weight: 2, stack: 50,
    recipe: { time: SPIN_WHEEL_TIME, materials: { Flax: 1 },
              source: { station: CraftingStation.Windmill }, number: 1 } },
  { type: 'item', id: 'Barley', weight: 0.2, stack: 100,
    recipe: { time: 4500, materials: { Barley: 1 },
              source: { station: CraftingStation.Cultivator }, number: 2 } },
  { type: 'item', id: 'BarleyFlour', weight: 0.2, stack: 20,
    recipe: { time: -1, materials: { Barley: 1 },
              source: { station: CraftingStation.Windmill }, number: 1 } },
  { type: 'food', id: 'Cloudberry', weight: 0.1, stack: 50,
    health: 15, stamina: 25, duration: 800, regen: 1 },
  { type: 'item', id: 'LoxMeat', weight: 1, stack: 20 },
  { type: 'item', id: 'LoxPelt', weight: 1, stack: 50 },
  { type: 'food', id: 'CookedLoxMeat', weight: 1, stack: 20,
    health: 70, stamina: 40, duration: 2000, regen: 3,
    recipe: { time: CAULDRON_TIME, materials: { RawMeat: 1 },
              source: { station: CraftingStation.CookingStation }, number: 1 } },
  { type: 'food', id: 'BloodPudding', weight: 1, stack: 10,
    health: 90, stamina: 50, duration: 2400, regen: 4,
    recipe: { time: CAULDRON_TIME, materials: { Bloodbag: 2, BarleyFlour: 4, Thistle: 2 },
              source: { station: CraftingStation.Cauldron }, number: 1 } },
  { type: 'food', id: 'Bread', weight: 1, stack: 10,
    health: 40, stamina: 70, duration: 1800, regen: 2,
    recipe: { time: CAULDRON_TIME, materials: { BarleyFlour: 10 },
              source: { station: CraftingStation.Cauldron }, number: 1 } },
  { type: 'food', id: 'FishWraps', weight: 1, stack: 10,
    health: 60, stamina: 90, duration: 2400, regen: 4,
    recipe: { time: CAULDRON_TIME, materials: { CookedFish: 2, BarleyFlour: 4 },
              source: { station: CraftingStation.Cauldron }, number: 1 } },
  { type: 'food', id: 'LoxMeatPie', weight: 1, stack: 20,
    health: 80, stamina: 80, duration: 2400, regen: 4,
    recipe: { time: CAULDRON_TIME, materials: { BarleyFlour: 4, Cloudberry: 2, CookedLoxMeat: 2 },
              source: { station: CraftingStation.CookingStation }, number: 1 } },
  { type: 'item', id: 'Needle', weight: 0.5, stack: 50 },
  { type: 'item', id: 'BlackMetalScrap', weight: 10, stack: 30, teleportable: false },
  { type: 'item', id: 'BlackMetal', weight: 12, stack: 30, teleportable: false,
    recipe: { time: FURNACE_TIME, materials: { BlackMetalScrap: 1, Coal: 2 },
              source: { station: CraftingStation.BlastFurnace }, number: 1 } },
  { type: 'item', id: 'GoblinTotem', weight: 1, stack: 30 },
  { type: 'item', id: 'TrophyLox', weight: 2, stack: 20 },
  { type: 'item', id: 'TrophyDeathsquito', weight: 0.5, stack: 20 },
  { type: 'item', id: 'TrophyGoblin', weight: 2, stack: 20 },
  { type: 'item', id: 'TrophyGoblinBrute', weight: 2, stack: 20 },
  { type: 'item', id: 'TrophyGoblinKing', weight: 1, stack: 20 },
  { type: 'item', id: 'Yagluththing', weight: 0.1, stack: 1 },
// FLAME
  { type: 'item', id: 'FlametalOre', weight: 12, stack: 30, teleportable: false },
  { type: 'item', id: 'Flametal', weight: 12, stack: 30, teleportable: false,
    recipe: { time: FURNACE_TIME, materials: { FlametalOre: 1, Coal: 2 },
              source: { station: CraftingStation.BlastFurnace }, number: 1 } },
];
