import { Item } from "../types";

export const resources: Item[] = [
  { type: 'item', id: 'Wood', weight: 2, stack: 50, teleportable: true },
  { type: 'item', id: 'Resin', weight: 0.3, stack: 50, teleportable: true },
  { type: 'item', id: 'Feathers', weight: 0.1, stack: 50, teleportable: true },
  { type: 'item', id: 'Stone', weight: 2, stack: 50, teleportable: true },
  { type: 'item', id: 'Flint', weight: 2, stack: 30, teleportable: true },
  { type: 'item', id: 'LeatherScraps', weight: 0.5, stack: 50, teleportable: true },
  { type: 'item', id: 'DeerHide', weight: 1, stack: 50, teleportable: true },
  { type: 'item', id: 'QueenBee', weight: 0.2, stack: 20, teleportable: true },
  { type: 'food', id: 'Raspberry', weight: 0.1, stack: 50, teleportable: true,
    health: 10, stamina: 20, duration: 600, regen: 1 },
  { type: 'food', id: 'Mushroom', weight: 0.1, stack: 50, teleportable: true,
    health: 15, stamina: 20, duration: 600, regen: 1 },
  { type: 'food', id: 'Honey', weight: 0.2, stack: 50, teleportable: true,
    health: 20, stamina: 20, duration: 300, regen: 5 },
  { type: 'item', id: 'RawMeat', weight: 1, stack: 20, teleportable: true },
  { type: 'food', id: 'CookedMeat', weight: 1, stack: 20, teleportable: true,
    health: 40, stamina: 30, duration: 1200, regen: 2 },
  { type: 'item', id: 'NeckTail', weight: 0.5, stack: 50, teleportable: true },
  { type: 'food', id: 'NeckTailGrilled', weight: 0.5, stack: 50, teleportable: true,
    health: 35, stamina: 20, duration: 1000, regen: 2 },
  { type: 'item', id: 'TrophyBoar', weight: 2, stack: 50, teleportable: true },
  { type: 'item', id: 'TrophyDeer', weight: 2, stack: 50, teleportable: true },
  { type: 'item', id: 'TrophyNeck', weight: 0.5, stack: 50, teleportable: true },
  { type: 'item', id: 'TrophyEikthyr', weight: 2, stack: 20, teleportable: true },
  { type: 'item', id: 'HardAntler', weight: 2, stack: 50, teleportable: true },

  { type: 'item', id: 'FineWood', weight: 2, stack: 50, teleportable: true },
  { type: 'item', id: 'GreydwarfEye', weight: 0.2, stack: 50, teleportable: true },
  { type: 'item', id: 'BoneFragments', weight: 0.5, stack: 50, teleportable: true },
  { type: 'item', id: 'SurtlingCore', weight: 5, stack: 10, teleportable: true },
  { type: 'item', id: 'AncientSeed', weight: 1, stack: 50, teleportable: true },
  { type: 'item', id: 'RoundLog', weight: 2, stack: 50, teleportable: true },
  { type: 'item', id: 'CarrotSeeds', weight: 0.1, stack: 100, teleportable: true },
  { type: 'food', id: 'Blueberries', weight: 0.1, stack: 50, teleportable: true,
    health: 15, stamina: 20, duration: 600, regen: 1 },
  { type: 'food', id: 'MushroomYellow', weight: 0.1, stack: 50, teleportable: true,
    health: 20, stamina: 20, duration: 600, regen: 1 },
  { type: 'food', id: 'Carrot', weight: 0.3, stack: 50, teleportable: true,
    health: 15, stamina: 15, duration: 600, regen: 1 },
  { type: 'food', id: 'CarrotSoup', weight: 1, stack: 10, teleportable: true,
    health: 20, stamina: 60, duration: 1500, regen: 2 },

  { type: 'item', id: 'Turnip', weight: 0.3, stack: 50, teleportable: true },
  { type: 'food', id: 'TurnipStew', weight: 1, stack: 10, teleportable: true,
    health: 50, stamina: 50, duration: 1600, regen: 2 },
  { type: 'item', id: 'ElderBark', weight: 2, stack: 50, teleportable: true },

//{ type: 'item', id: 'WolfPelt', weight: 1, stack: 50, teleportable: true },
//{ type: 'item', id: 'WolfFang', weight: 0.1, stack: 50, teleportable: true },*/

  { type: 'item', id: 'TrophyFenring', weight: 2, stack: 20, teleportable: true },
];
