import { AttackAnimation, CraftingStation, Shield, Weapon } from "../types";
import { SkillType } from "./skills";

const CRAFT_TIME = 4;
const disabled = true;

export const animations: Record<AttackAnimation, number[]> = {
  swing_pickaxe: [1.4], // verified
  spear_throw: [1.57],
  spear_poke: [0.67],
  throw_bomb: [0.95],
  knife_stab: [0.88, 0.54, 0.62], // verified sum
  knife_secondary: [1.72], // ~1.6?
  swing_axe: [0.73, 0.69, 1.12], // 0.56, 1.30, 2.00    4.20, 4.93, 5.46, 6.50   1.26, 2.13, 2.83, 4.00
  unarmed_attack: [0.76, 0.76],
  unarmed_kick: [1.51],
  swing_sledge: [2.23],
  swing_longsword: [1.02, 0.68, 0.76],
  sword_secondary: [1.84],
  mace_secondary: [1.72],
  battleaxe_attack: [1.82, 0.92, 0.7],
  battleaxe_secondary: [0.94],
  atgeir_attack: [0.84, 0.86, 1.28],
  atgeir_secondary: [1.74],
  bow_fire: [0.83],
};
// bow_aim_recoil: 21

export const items: (Weapon | Shield)[] = [
// PRE-CRAFT AGE
  { type: 'weapon', slot: 'both',
    id: 'Hands',
    emoji: '👊',
    tier: 0,
    weight: 0, stack: 0,
    skill: SkillType.Unarmed,
    damage: [{ blunt: 5 }, {}],
    attacks: [{
      type: 'melee',
      animation: 'unarmed_attack',
      chain: 2,
      chainCombo: 1,
      stamina: 5,
      range: 1.5,
    }, {
      type: 'melee',
      animation: 'unarmed_kick',
      chain: 0,
      chainCombo: 1,
      stamina: 10,
      range: 1.6,
      mul: { damage: 1, force: 4, stagger: 6 },
    }],
    maxLvl: 1,
    durability: [100, 50],
    block: 5,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 40, backstab: 4, moveSpeed: 0,
  },
  { type: 'weapon', slot: 'primary',
    id: 'Club',
    emoji: '🏏',
    tier: 0,
    weight: 2, stack: 1,
    floating: true,
    skill: SkillType.Clubs,
    damage: [{ blunt: 12 }, { blunt: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 2.4,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 20,
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 6 },
      materialsPerLevel: { BoneFragments: 5 },
      source: { station: CraftingStation.Inventory, level: 0 },
      upgrade: { station: CraftingStation.Workbench, level: 1 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'AxeStone',
    emoji: '🪓',
    tier: 0,
    toolTier: 0,
    weight: 1.5, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      slash: 15,
      chop: 20,
    }, {
      slash: 5,
      chop: 3,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_axe',
      chain: 2,
      chainCombo: 2,
      stamina: 5,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [100, 30],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 5, Stone: 4 },
      materialsPerLevel: { Stone: 2 },
      source: { station: CraftingStation.Inventory, level: 0 },
      upgrade: { station: CraftingStation.Workbench, level: 1 },
    }
  },
  { type: 'weapon', slot: 'either',
    id: 'Torch',
    emoji: '🔥',
    tier: 0,
    tags: ['fire'],
    weight: 1, stack: 1,
    skill: SkillType.Clubs,
    damage: [{ blunt: 4, fire: 15 }, {}],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 2.4,
    }],
    maxLvl: 1,
    durability: [20, 0],
    durabilityDrainPerSec: 30,
    block: 10,
    parryForce: [10, 5],
    parryBonus: 2,
    knockback: 30, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 1, Resin: 1 },
      materialsPerLevel: {},
      source: { station: CraftingStation.Inventory, level: 0 },
      upgrade: { station: CraftingStation.Inventory, level: 0 },
    }
  },
// STONE AGE
  { type: 'weapon', slot: 'primary',
    id: 'AxeFlint',
    emoji: '🪓',
    tier: 1,
    toolTier: 1,
    weight: 1.5, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      slash: 20,
      chop: 30,
    }, {
      slash: 5,
      chop: 3,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_axe',
      chain: 3,
      chainCombo: 2,
      stamina: 8,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [100, 30],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 4, Flint: 6 },
      materialsPerLevel: { Flint: 3, LeatherScraps: 2 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'KnifeFlint',
    emoji: '🔪',
    tier: 1,
    weight: 0.3, stack: 1,
    skill: SkillType.Knives,
    damage: [{
      slash: 6,
      pierce: 6,
    }, {
      slash: 1,
      pierce: 1,
    }],
    attacks: [{
      type: 'melee',
      animation: 'knife_stab',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 1.8,
    }, {
      type: 'melee',
      animation: 'knife_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 40,
      range: 1.8,
      mul: { damage: 3, force: 4, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 5,
    parryForce: [10, 5],
    parryBonus: 4,
    knockback: 10, backstab: 10, moveSpeed: 0,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 2, Flint: 4, LeatherScraps: 2 },
      materialsPerLevel: { Flint: 2 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'SpearFlint',
    emoji: '🍢',
    tier: 1,
    weight: 1.5, stack: 1,
    floating: true,
    skill: SkillType.Spears,
    damage: [{ pierce: 20 }, { pierce: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'spear_poke',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1.8,
    }, {
      type: 'proj',
      animation: 'spear_throw',
      projVel: [2, 20],
      projAcc: [20, 1],
      stamina: 15,
      range: 1,
      mul: { damage: 1.5, force: 1.5, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 20, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 5, Flint: 10, LeatherScraps: 2 },
      materialsPerLevel: { Wood: 3, Flint: 5, LeatherScraps: 1 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weapon', slot: 'both',
    id: 'SledgeStagbreaker',
    emoji: '🔨',
    tier: 1,
    weight: 4, stack: 1,
    floating: true,
    skill: SkillType.Clubs,
    damage: [
      { blunt: 20, pierce: 5 },
      { blunt: 6 }
    ],
    attacks: [{
      type: 'area',
      animation: 'swing_sledge',
      chain: 0,
      chainCombo: 2,
      stamina: 25,
      range: 2.4,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 15,
    parryForce: [50, 10],
    parryBonus: 2,
    knockback: 150, backstab: 2, moveSpeed: -0.2,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { RoundLog: 20, DeerTrophy: 5, LeatherScraps: 2 },
      materialsPerLevel: { RoundLog: 5, DeerTrophy: 2, LeatherScraps: 1, BoneFragments: 10 },
      source: { station: CraftingStation.Workbench, level: 2 },
      upgrade: { station: CraftingStation.Workbench, level: 3 },
    }
  },
  { type: 'weapon', slot: 'bow',
    id: 'Bow',
    emoji: '🏹',
    tier: 1,
    weight: 1.5, stack: 1,
    floating: true,
    skill: SkillType.Bows,
    damage: [{ pierce: 22 }, { pierce: 3 }],
    attacks: [{
      type: 'proj',
      animation: 'bow_fire',
      projVel: [2, 35],
      projAcc: [20, 1],
      stamina: 0,
      range: 1,
    }],
    maxLvl: 4,
    durability: [50, 50],
    block: 5,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 0, backstab: 3, moveSpeed: -0.05,
    holdDurationMin: 2.5,
    holdStaminaDrain: 5,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 10, LeatherScraps: 8 },
      materialsPerLevel: { Wood: 5, LeatherScraps: 4, DeerHide: 1 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weapon', slot: 'both',
    id: 'PickaxeStone',
    emoji: '⛏️',
    disabled,
    tier: -1,
    toolTier: 0,
    weight: 2, stack: 1,
    skill: SkillType.Pickaxes,
    damage: [{
      pierce: 15,
      pickaxe: 15,
    }, {}],
    attacks: [{
      type: 'melee',
      animation: 'swing_pickaxe',
      chain: 0,
      chainCombo: 2,
      stamina: 10,
      range: 1.8,
    }],
    maxLvl: 1,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
  },
  { type: 'weapon', slot: 'both',
    id: 'PickaxeAntler',
    emoji: '⛏️',
    tier: 1,
    toolTier: 0,
    weight: 2, stack: 1,
    skill: SkillType.Pickaxes,
    damage: [{
      pierce: 18,
      pickaxe: 18,
    }, {}],
    attacks: [{
      type: 'melee',
      animation: 'swing_pickaxe',
      chain: 0,
      chainCombo: 2,
      stamina: 10,
      range: 1.8,
    }],
    maxLvl: 1,
    durability: [100, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 10, HardAntler: 1 },
      materialsPerLevel: {},
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 0 },
    }
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldWood',
    emoji: '🛡️',
    tier: 1,
    weight: 4, stack: 1,
    floating: true,
    skill: SkillType.Blocking,
    maxLvl: 3,
    durability: [200, 50],
    block: [20, 5],
    parryForce: 0,
    parryBonus: 1.5,
    moveSpeed: -0.2,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 10, Resin: 4, LeatherScraps: 4 },
      materialsPerLevel: { Wood: 5, Resin: 2, LeatherScraps: 2 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldWoodTower',
    emoji: '🛡️',
    tier: 1,
    weight: 4, stack: 1,
    floating: true,
    skill: SkillType.Blocking,
    maxLvl: 3,
    durability: [200, 50],
    block: [35, 5],
    parryForce: 0,
    parryBonus: 1,
    moveSpeed: -0.2,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 10, LeatherScraps: 6 },
      materialsPerLevel: { Wood: 5, LeatherScraps: 3 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
// BRONZE AGE
  { type: 'weapon', slot: 'primary',
    id: 'KnifeCopper',
    emoji: '🔪',
    tier: 2,
    weight: 0.3, stack: 1,
    skill: SkillType.Knives,
    damage: [{
      slash: 9,
      pierce: 9,
    }, {
      slash: 1,
      pierce: 1,
    }],
    attacks: [{
      type: 'melee',
      animation: 'knife_stab',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 1.8,
    }, {
      type: 'melee',
      animation: 'knife_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 40,
      range: 1.8,
      mul: { damage: 3, force: 4, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 8,
    parryForce: [10, 5],
    parryBonus: 4,
    knockback: 10, backstab: 10, moveSpeed: 0,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 2, Copper: 8 },
      materialsPerLevel: { GreydwarfEye: 8, Copper: 4 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'AtgeirBronze',
    emoji: '🔱',
    tier: 2,
    weight: 2.5, stack: 1,
    skill: SkillType.Polearms,
    damage: [{ pierce: 45 }, { pierce: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'atgeir_attack',
      chain: 3,
      chainCombo: 2,
      stamina: 20,
      range: 3.2,
    }, {
      type: 'melee',
      animation: 'atgeir_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 35,
      range: 3,
      mul: { damage: 1, force: 10, stagger: 6 },
    }],
    maxLvl: 4,
    durability: [125, 50],
    block: 10,
    parryForce: [40, 5],
    parryBonus: 3,
    knockback: 30, backstab: 3, moveSpeed: -0.1,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 10, Bronze: 8, LeatherScraps: 2 },
      materialsPerLevel: { Bronze: 4 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'AxeBronze',
    emoji: '🪓',
    tier: 2,
    toolTier: 2,
    weight: 2, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      slash: 35,
      chop: 40,
    }, {
      slash: 5,
      chop: 3,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_axe',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [125, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 4, Bronze: 8, LeatherScraps: 2 },
      materialsPerLevel: { Bronze: 4, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'MaceBronze',
    emoji: '🏏',
    tier: 2,
    weight: 2, stack: 1,
    floating: true,
    skill: SkillType.Clubs,
    damage: [{ blunt: 35  }, { blunt: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 15,
      range: 2.4,
    }, {
      type: 'melee',
      animation: 'mace_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.5,
      mul: { damage: 2.5, force: 2, stagger: 2 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [30, 5],
    parryBonus: 2,
    knockback: 80, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 4, Bronze: 8, LeatherScraps: 3 },
      materialsPerLevel: { Bronze: 4 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'SpearBronze',
    emoji: '🍢',
    tier: 2,
    weight: 1.5, stack: 1,
    floating: true,
    skill: SkillType.Spears,
    damage: [{ pierce: 35 }, { pierce: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'spear_poke',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1.8,
    }, {
      type: 'proj',
      animation: 'spear_throw',
      projVel: [2, 20],
      projAcc: [20, 1],
      stamina: 15,
      range: 1,
      mul: { damage: 1.5, force: 1.5, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 20, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 5, Bronze: 6, DeerHide: 2 },
      materialsPerLevel: { Wood: 3, Bronze: 4, DeerHide: 1 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'SwordBronze',
    emoji: '🗡️',
    tier: 2,
    weight: 0.8, stack: 1,
    skill: SkillType.Swords,
    damage: [{ slash: 35 }, { slash: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      animation: 'sword_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 2, Bronze: 8, LeatherScraps: 2 },
      materialsPerLevel: { Wood: 1, Bronze: 4, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weapon', slot: 'both',
    id: 'PickaxeBronze',
    emoji: '⛏️',
    tier: 2,
    toolTier: 1,
    weight: 2, stack: 1,
    skill: SkillType.Pickaxes,
    damage: [{
      pierce: 25,
      pickaxe: 25,
    }, {
      pierce: 5,
      pickaxe: 4,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_pickaxe',
      chain: 0,
      chainCombo: 2,
      stamina: 10,
      range: 1.8,
    }],
    maxLvl: 4,
    durability: [120, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { RoundLog: 3, Bronze: 10 },
      materialsPerLevel: { RoundLog: 1, Bronze: 5 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weapon', slot: 'bow',
    id: 'BowFineWood',
    emoji: '🏹',
    tier: 2,
    weight: 1.5, stack: 1,
    floating: true,
    skill: SkillType.Bows,
    damage: [{ pierce: 32 }, { pierce: 3 }],
    attacks: [{
      type: 'proj',
      animation: 'bow_fire',
      projVel: [2, 50],
      projAcc: [20, 1],
      stamina: 0,
      range: 1,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 5,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 5, backstab: 3, moveSpeed: -0.05,
    holdDurationMin: 2.5,
    holdStaminaDrain: 5,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 10, RoundLog: 10, DeerHide: 2 },
      materialsPerLevel: { FineWood: 5, RoundLog: 5, DeerHide: 2 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldBronzeBuckler',
    emoji: '🛡️',
    tier: 2,
    weight: 3, stack: 1,
    skill: SkillType.Blocking,
    maxLvl: 3,
    durability: [200, 50],
    block: [45, 5],
    parryForce: 30,
    parryBonus: 2,
    moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 4, Bronze: 10 },
      materialsPerLevel: { Wood: 1, Bronze: 5 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
// IRON AGE
  { type: 'weapon', slot: 'primary',
    id: 'BombOoze',
    emoji: '💣',
    tier: 3,
    weight: 0.3, stack: 50,
    skill: null,
    damage: [{ blunt: 5, poison: 30 }, {}],
    attacks: [{
      type: 'proj',
      animation: 'throw_bomb',
      projVel: [2, 20],
      projAcc: [20, 5],
      stamina: 15,
      range: 1.5,
    }],
    maxLvl: 1,
    durability: [Infinity, 0],
    block: 4,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 40, backstab: 3, moveSpeed: 0,
    recipe: {
      type: 'craft_one',
      time: CRAFT_TIME,
      materials: { LeatherScraps: 5, Ooze: 10, Resin: 3 },
      source: { station: CraftingStation.Workbench, level: 1 },
      number: 5,
    }
  },
  { type: 'weapon', slot: 'both',
    id: 'Battleaxe',
    emoji: '🪓',
    tier: 3,
    toolTier: 3,
    weight: 2.5, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      slash: 75,
      chop: 40,
    }, {
      slash: 6,
      chop: 2.5,
    }],
    attacks: [{
      type: 'melee',
      animation: 'battleaxe_attack',
      chain: 3,
      chainCombo: 2,
      stamina: 25,
      range: 2.5,
    }, {
      type: 'melee',
      animation: 'battleaxe_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 2.5,
      mul: { damage: 0.5, force: 2, stagger: 4 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 20,
    parryForce: [70, 5],
    parryBonus: 2,
    knockback: 70, backstab: 3, moveSpeed: -0.2,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { ElderBark: 30, Iron: 35, LeatherScraps: 4 },
      materialsPerLevel: { ElderBark: 5, Iron: 15 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'SwordIron',
    emoji: '🗡️',
    tier: 3,
    toolTier: 0,
    weight: 0.8, stack: 1,
    skill: SkillType.Swords,
    damage: [{ slash: 55 }, { slash: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      animation: 'sword_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 2, Iron: 20, LeatherScraps: 3 },
      materialsPerLevel: { Wood: 1, Iron: 10, LeatherScraps: 2 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weapon', slot: 'primary',
    id: 'AxeIron',
    emoji: '🪓',
    tier: 3,
    toolTier: 3,
    weight: 2, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      slash: 55,
      chop: 50,
    }, {
      slash: 5,
      chop: 3,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_axe',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [175, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 4, Iron: 20, LeatherScraps: 2 },
      materialsPerLevel: { Iron: 10, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weapon', slot: 'both',
    id: 'SledgeIron',
    emoji: '🔨',
    tier: 3,
    weight: 4, stack: 1,
    skill: SkillType.Clubs,
    damage: [{ blunt: 55 }, { blunt: 6 }],
    attacks: [{
      type: 'area',
      animation: 'swing_sledge',
      chain: 0,
      chainCombo: 2,
      stamina: 25,
      range: 2,
      mul: { damage: 1, force: 1, stagger: 2 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 15,
    parryForce: [50, 10],
    parryBonus: 2,
    knockback: 200, backstab: 2, moveSpeed: -0.2,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { ElderBark: 10, Iron: 30, YmirRemains: 4, TrophyDraugrElite: 1 },
      materialsPerLevel: { ElderBark: 2, Iron: 15, YmirRemains: 2 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weapon', slot: 'primary',
    id: 'MaceIron',
    emoji: '🏏',
    tier: 3,
    weight: 2, stack: 1,
    floating: true,
    skill: SkillType.Clubs,
    damage: [{ blunt: 55 }, { blunt: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 15,
      range: 2.4,
    }, {
      type: 'melee',
      animation: 'mace_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.5,
      mul: { damage: 2.5, force: 2, stagger: 2 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [30, 5],
    parryBonus: 2,
    knockback: 90, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 4, Iron: 20, LeatherScraps: 3 },
      materialsPerLevel: { Iron: 10 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weapon', slot: 'primary',
    id: 'SpearElderbark',
    emoji: '🍢',
    tier: 3,
    weight: 1.5, stack: 1,
    floating: true,
    skill: SkillType.Spears,
    damage: [{ pierce: 55 }, { pierce: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'spear_poke',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1.8,
    }, {
      type: 'proj',
      animation: 'spear_throw',
      projVel: [2, 20],
      projAcc: [20, 1],
      stamina: 15,
      range: 1,
      mul: { damage: 1.5, force: 1.5, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 20, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { ElderBark: 10, Iron: 10, TrollHide: 4 },
      materialsPerLevel: { Wood: 5, Flint: 5, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'weapon', slot: 'both',
    id: 'PickaxeIron',
    emoji: '⛏️',
    tier: 3,
    toolTier: 2,
    weight: 2, stack: 1,
    skill: SkillType.Pickaxes,
    damage: [{
      pierce: 33,
      pickaxe: 33,
    }, {
      pierce: 5,
      pickaxe: 5,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_pickaxe',
      chain: 0,
      chainCombo: 2,
      stamina: 10,
      range: 1.8,
    }],
    maxLvl: 4,
    durability: [150, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { RoundLog: 3, Iron: 20 },
      materialsPerLevel: { RoundLog: 1, Iron: 10 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weapon', slot: 'both',
    id: 'AtgeirIron',
    emoji: '🔱',
    tier: 3,
    weight: 2.5, stack: 1,
    skill: SkillType.Polearms,
    damage: [{ pierce: 65 }, { pierce: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'atgeir_attack',
      chain: 3,
      chainCombo: 2,
      stamina: 20,
      range: 3.2,
    }, {
      type: 'melee',
      animation: 'atgeir_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 35,
      range: 3,
      mul: { damage: 1, force: 10, stagger: 6 },
    }],
    maxLvl: 4,
    durability: [175, 50],
    block: 10,
    parryForce: [40, 5],
    parryBonus: 3,
    knockback: 30, backstab: 3, moveSpeed: -0.1,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 10, Iron: 30, LeatherScraps: 2 },
      materialsPerLevel: { Iron: 15, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weapon', slot: 'bow',
    id: 'BowHuntsman',
    emoji: '🏹',
    tier: 3,
    weight: 1.5, stack: 1,
    floating: true,
    skill: SkillType.Bows,
    damage: [{ pierce: 42 }, { pierce: 3 }],
    attacks: [{
      type: 'proj',
      animation: 'bow_fire',
      projVel: [2, 50],
      projAcc: [20, 0],
      stamina: 0,
      range: 1,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 5,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 10, backstab: 3, moveSpeed: -0.05,
    holdDurationMin: 2.5,
    holdStaminaDrain: 5,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 10, Iron: 20, Feathers: 10, DeerHide: 2 },
      materialsPerLevel: { FineWood: 5, Iron: 10, Feathers: 5, DeerHide: 2 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldBanded',
    emoji: '🛡️',
    tier: 3,
    weight: 5, stack: 1,
    floating: true,
    skill: SkillType.Blocking,
    damage: { blunt: 10 },
    maxLvl: 3,
    durability: [200, 50],
    block: [60, 5],
    parryForce: [40, 5],
    parryBonus: 2,
    knockback: 50, backstab: 2, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 10, Iron: 8 },
      materialsPerLevel: { FineWood: 10, Iron: 4 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldIronTower',
    emoji: '🛡️',
    floating: true,
    tier: 3,
    weight: 4, stack: 1,
    skill: SkillType.Blocking,
    maxLvl: 3,
    durability: [200, 50],
    block: [75, 5],
    parryForce: 0,
    parryBonus: 1,
    knockback: 40, backstab: 4, moveSpeed: -0.2,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 15, Iron: 10 },
      materialsPerLevel: { FineWood: 10, Iron: 5 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
// SILVER AGE
  { type: 'weapon', slot: 'primary',
    id: 'SwordSilver',
    emoji: '🗡️',
    tier: 4,
    weight: 1, stack: 1,
    skill: SkillType.Swords,
    damage: [{
      slash: 75,
      spirit: 30,
    }, {
      slash: 6,
      spirit: 5,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      animation: 'sword_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { Wood: 2, Silver: 40, LeatherScraps: 3, Iron: 5 },
      materialsPerLevel: { Wood: 1, Silver: 20, LeatherScraps: 1, Iron: 3 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'SpearWolfFang',
    emoji: '🍢',
    tier: 4,
    weight: 1.5, stack: 1,
    floating: true,
    skill: SkillType.Spears,
    damage: [{ pierce: 70 }, { pierce: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'spear_poke',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1.8,
    }, {
      type: 'proj',
      animation: 'spear_throw',
      projVel: [2, 20],
      projAcc: [20, 1],
      stamina: 15,
      range: 1,
      mul: { damage: 1.5, force: 1.5, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 20, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { ElderBark: 10, WolfFang: 4, Silver: 2, LeatherScraps: 2 },
      materialsPerLevel: { ElderBark: 5, WolfFang: 2, Silver: 1, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'MaceSilver',
    emoji: '🔨',
    tier: 4,
    weight: 2, stack: 1,
    skill: SkillType.Clubs,
    damage: [{
      blunt: 35,
      frost: 40,
      spirit: 20,
    }, {
      frost: 6,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      stamina: 20,
      range: 2.4,
      chainCombo: 2,
    }, {
      type: 'melee',
      animation: 'mace_secondary',
      chain: 0,
      stamina: 30,
      range: 2.5,
      mul: { damage: 2.5, force: 2, stagger: 2, },
      chainCombo: 2,
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [30, 5],
    parryBonus: 2,
    knockback: 120, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { ElderBark: 10, Silver: 30, YmirRemains: 5, FreezeGland: 5 },
      materialsPerLevel: { Silver: 15 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'SpearChitin',
    emoji: '🍢',
    tier: 3,
    special: 'harpoon',
    weight: 0.3, stack: 1,
    floating: true,
    skill: SkillType.Spears,
    damage: [{ pierce: 10 }, {}],
    attacks: [{
      type: 'proj',
      animation: 'spear_throw',
      projVel: [2, 20],
      projAcc: [20, 1],
      stamina: 15,
      range: 1,
    }],
    maxLvl: 1,
    durability: [50, 0],
    block: 10,
    parryForce: 20,
    parryBonus: 2,
    knockback: 20, backstab: 1, moveSpeed: -0.05,
    recipe: {
      type: 'craft_one',
      time: CRAFT_TIME,
      materials: { FineWood: 8, Chitin: 30, LeatherScraps: 3 },
      source: { station: CraftingStation.Forge, level: 2 },
      number: 1,
    }
  },
  { type: 'weapon', slot: 'primary',
    id: 'KnifeChitin',
    emoji: '🔪',
    tier: 3,
    weight: 0.3, stack: 1,
    floating: true,
    skill: SkillType.Knives,
    damage: [{
      slash: 12,
      pierce: 12,
    }, {
      slash: 1,
      pierce: 1,
    }],
    attacks: [{
      type: 'melee',
      animation: 'knife_stab',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 1.8,
    }, {
      type: 'melee',
      animation: 'knife_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 40,
      range: 1.8,
      mul: { damage: 3, force: 4, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: [10, 5],
    parryBonus: 4,
    knockback: 10, backstab: 10, moveSpeed: 0,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 4, Chitin: 20, LeatherScraps: 2 },
      materialsPerLevel: { Chitin: 10 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
  { type: 'weapon', slot: 'bow',
    id: 'BowDraugrFang',
    emoji: '🏹',
    tier: 4,
    weight: 1.5, stack: 1,
    floating: true,
    skill: SkillType.Bows,
    damage: [{
      pierce: 47,
      poison: 5,
    }, {
      pierce: 3,
      poison: 5,
    }],
    attacks: [{
      type: 'proj',
      animation: 'bow_fire',
      projVel: [2, 60],
      projAcc: [20, 0],
      stamina: 0,
      range: 1,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 5,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 10, backstab: 3, moveSpeed: -0.05,
    holdDurationMin: 2.5,
    holdStaminaDrain: 5,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { ElderBark: 10, Silver: 20, DeerHide: 2, Guck: 10, },
      materialsPerLevel: { ElderBark: 5, Silver: 10, DeerHide: 2, Guck: 2 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldSilver',
    emoji: '🛡️',
    tier: 4,
    weight: 5, stack: 1,
    floating: true,
    skill: SkillType.Blocking,
    damage: { blunt: 10 },
    maxLvl: 3,
    durability: [200, 50],
    block: [75, 5],
    parryForce: [40, 5],
    parryBonus: 1.5,
    knockback: 50, backstab: 4, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 10, Silver: 8 },
      materialsPerLevel: { FineWood: 10, Silver: 4 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldSerpentscale',
    emoji: '🛡️',
    tier: 4,
    weight: 5, stack: 1,
    floating: true,
    skill: SkillType.Blocking,
    damage: { blunt: 10 },
    maxLvl: 3,
    durability: [250, 50],
    block: [90, 5],
    parryForce: [50, 5],
    parryBonus: 1,
    knockback: 50, backstab: 4, moveSpeed: -0.1,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 10, Iron: 4, SerpentScale: 8 },
      materialsPerLevel: { FineWood: 10, Iron: 2, SerpentScale: 4 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
// BLACK AGE
  { type: 'weapon', slot: 'both',
    id: 'AtgeirBlackmetal',
    emoji: '🔱',
    tier: 5,
    weight: 2.5, stack: 1,
    skill: SkillType.Polearms,
    damage: [{ pierce: 105 }, { pierce: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'atgeir_attack',
      chain: 3,
      chainCombo: 2,
      stamina: 20,
      range: 3.2,
    }, {
      type: 'melee',
      animation: 'atgeir_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 35,
      range: 3,
      mul: { damage: 1, force: 10, stagger: 6 },
    }],
    maxLvl: 4,
    durability: [175, 50],
    block: 10,
    parryForce: [40, 5],
    parryBonus: 3,
    knockback: 30, backstab: 3, moveSpeed: -0.1,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 10, BlackMetal: 30, LinenThread: 5 },
      materialsPerLevel: { BlackMetal: 15, LinenThread: 5 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'weapon', slot: 'primary',
    id: 'AxeBlackMetal',
    emoji: '🪓',
    tier: 5,
    toolTier: 4,
    weight: 2, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      slash: 95,
      chop: 60,
    }, {
      slash: 5,
      chop: 3,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_axe',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [175, 50],
    block: 20,
    parryForce: 0,
    parryBonus: 2,
    knockback: 60, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 6, BlackMetal: 20, LinenThread: 5 },
      materialsPerLevel: { BlackMetal: 10, LinenThread: 5 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'weapon', slot: 'primary',
    id: 'KnifeBlackMetal',
    emoji: '🔪',
    tier: 5,
    weight: 0.3, stack: 1,
    skill: SkillType.Knives,
    damage: [{
      slash: 18,
      pierce: 18,
    }, {
      slash: 1,
      pierce: 1,
    }],
    attacks: [{
      type: 'melee',
      animation: 'knife_stab',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 1.8,
    }, {
      type: 'melee',
      animation: 'knife_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 40,
      range: 1.8,
      mul: { damage: 3, force: 4, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 15,
    parryForce: [10, 5],
    parryBonus: 4,
    knockback: 10, backstab: 10, moveSpeed: 0,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 4, BlackMetal: 10, LinenThread: 5 },
      materialsPerLevel: { BlackMetal: 4, LinenThread: 5 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'weapon', slot: 'primary',
    id: 'SwordBlackmetal',
    emoji: '🗡️',
    tier: 5,
    weight: 0.8, stack: 1,
    skill: SkillType.Swords,
    damage: [{ slash: 95 }, { slash: 6 }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      animation: 'sword_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 2, BlackMetal: 20, LinenThread: 5 },
      materialsPerLevel: { BlackMetal: 10, LinenThread: 5 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'weapon', slot: 'primary',
    id: 'MaceNeedle',
    emoji: '🏏',
    tier: 5,
    weight: 2, stack: 1,
    floating: true,
    skill: SkillType.Clubs,
    damage: [{
      blunt: 50,
      pierce: 45,
    }, {
      pierce: 6,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 15,
      range: 2.4,
    }, {
      type: 'melee',
      animation: 'mace_secondary',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.5,
      mul: { damage: 2.5, force: 2, stagger: 2 },
    }],
    maxLvl: 4,
    durability: [150, 50],
    block: 20,
    parryForce: [30, 5],
    parryBonus: 2,
    knockback: 90, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 5, Iron: 20, Needle: 5, LinenThread: 10 },
      materialsPerLevel: { Iron: 2, LinenThread: 2 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldBlackmetal',
    emoji: '🛡️',
    tier: 5,
    weight: 5, stack: 1,
    floating: true,
    skill: SkillType.Blocking,
    damage: { blunt: 10 },
    maxLvl: 3,
    durability: [200, 50],
    block: [90, 5],
    parryForce: [50, 5],
    parryBonus: 1.5,
    knockback: 50, backstab: 4, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 10, BlackMetal: 8, Chain: 5 },
      materialsPerLevel: { FineWood: 10, BlackMetal: 4, Chain: 2 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldBlackmetalTower',
    emoji: '🛡️',
    tier: 5,
    weight: 5, stack: 1,
    floating: true,
    skill: SkillType.Blocking,
    damage: { blunt: 10 },
    maxLvl: 3,
    durability: [200, 50],
    block: [105, 5],
    parryForce: [0, 5],
    parryBonus: 1,
    knockback: 50, backstab: 4, moveSpeed: -0.2,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 15, BlackMetal: 10, Chain: 7 },
      materialsPerLevel: { FineWood: 15, BlackMetal: 6, Chain: 3 },  
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
// FLAME AGE
  { type: 'weapon', slot: 'primary',
    id: 'SwordIronFire',
    emoji: '🗡️',
    disabled,
    tier: 6,
    toolTier: 0,
    weight: 1, stack: 1,
    skill: SkillType.Swords,
    damage: [{
      slash: 55,
      fire: 30,
    }, {
      slash: 5,
      fire: 6,
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      animation: 'sword_secondary',
      chain: 0,
      chainCombo: 0,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      type: 'craft_upg',
      time: CRAFT_TIME,
      materials: { FineWood: 2, Flametal: 20, SurtlingCore: 20, LeatherScraps: 3 },
      materialsPerLevel: { Flametal: 10, SurtlingCore: 10, LeatherScraps: 2 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldKnight',
    emoji: '🛡️',
    disabled,
    tier: -1,
    weight: 4, stack: 1,
    floating: true,
    skill: SkillType.Blocking,
    maxLvl: 1,
    durability: [100, 50],
    block: [120, 5],
    parryForce: 40,
    parryBonus: 1.5,
    knockback: 200, backstab: 4, moveSpeed: -0.05,
  },
  { type: 'shield', slot: 'secondary',
    id: 'ShieldIronSquare',
    emoji: '🛡️',
    disabled,
    tier: -1,
    weight: 4, stack: 1,
    floating: true,
    skill: SkillType.Blocking,
    maxLvl: 1,
    durability: [200, 50],
    block: [35, 5],
    parryForce: 30,
    parryBonus: 1,
    knockback: 200, backstab: 4, moveSpeed: -0.2,
  },
  { type: 'weapon', slot: 'primary',
    id: 'SwordCheat',
    emoji: '🗡️',
    disabled,
    tier: -1,
    toolTier: 10,
    weight: 1, stack: 1,
    skill: SkillType.Swords,
    damage: [{
      slash: 10000,
      chop: 10000,
      pickaxe: 10000,
    }, {
    }],
    attacks: [{
      type: 'melee',
      animation: 'swing_longsword',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      animation: 'sword_secondary',
      chain: 0,
      chainCombo: 0,
      stamina: 30,
      range: 2.4,
    }],
    maxLvl: 1,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
  },
];
