import { CraftingStation, DamageType, Weapon } from "../types";
import { SkillType } from "./skills";

const CRAFT_TIME = 4;

export const items: Weapon[] = [
// PRE-CRAFT AGE
  { type: 'weap', slot: 'primary',
    id: 'Club',
    tier: 0,
    weight: 2, stack: 1,
    skill: SkillType.Clubs,
    damage: [{
      [DamageType.Blunt]: 12
    }, {
      [DamageType.Blunt]: 6
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 2.4,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 20,
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 6 },
      materialsPerLevel: { BoneFragments: 5 },
      source: { station: CraftingStation.Inventory, level: 0 },
      upgrade: { station: CraftingStation.Workbench, level: 1 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'AxeStone',
    tier: 0,
    toolTier: 0,
    weight: 1.5, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      [DamageType.Slash]: 15,
      [DamageType.Chop]: 20,
    }, {
      [DamageType.Slash]: 5,
      [DamageType.Chop]: 3,
    }],
    attacks: [{
      type: 'melee',
      chain: 2,
      chainCombo: 2,
      stamina: 5,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [100, 30],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 5, Stone: 4 },
      materialsPerLevel: { Stone: 2 },
      source: { station: CraftingStation.Inventory, level: 0 },
      upgrade: { station: CraftingStation.Workbench, level: 1 },
    }
  },
  { type: 'weap', slot: 'either',
    id: 'Torch',
    tier: 0,
    weight: 1, stack: 1,
    skill: SkillType.Clubs,
    damage: [{
      [DamageType.Blunt]: 4,
      [DamageType.Fire]: 15,
    }, {}],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 2.4,
    }],
    maxLvl: 1,
    durability: [20, 0],
    block: 10,
    parryForce: [10, 5],
    parryBonus: 2,
    knockback: 30, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 1, Resin: 1 },
      materialsPerLevel: {},
      source: { station: CraftingStation.Inventory, level: 0 },
      upgrade: { station: CraftingStation.Inventory, level: 0 },
    }
  },
// STONE AGE
  { type: 'weap', slot: 'primary',
    id: 'AxeFlint',
    tier: 1,
    toolTier: 1,
    weight: 1.5, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      [DamageType.Slash]: 20,
      [DamageType.Chop]: 30,
    }, {
      [DamageType.Slash]: 5,
      [DamageType.Chop]: 3,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 8,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [100, 30],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 4, Flint: 6 },
      materialsPerLevel: { Flint: 3, LeatherScraps: 2 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'KnifeFlint',
    tier: 1,
    weight: 0.3, stack: 1,
    skill: SkillType.Knives,
    damage: [{
      [DamageType.Slash]: 6,
      [DamageType.Pierce]: 6,
    }, {
      [DamageType.Slash]: 1,
      [DamageType.Pierce]: 1,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 1.8,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 40,
      range: 1.8,
      mul: { damage: 3, force: 4, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 5,
    parryForce: [10, 5],
    parryBonus: 4,
    knockback: 10, backstab: 10, moveSpeed: 0,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 2, Flint: 4, LeatherScraps: 2 },
      materialsPerLevel: { Flint: 2 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'SpearFlint',
    tier: 1,
    weight: 1.5, stack: 1,
    skill: SkillType.Spears,
    damage: [{
      [DamageType.Pierce]: 20,
    }, {
      [DamageType.Pierce]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1.8,
    }, {
      type: 'proj',
      projVel: [2, 20],
      projAcc: [20, 1],
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1,
      mul: { damage: 1.5, force: 1.5, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 20, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 5, Flint: 10, LeatherScraps: 2 },
      materialsPerLevel: { Wood: 3, Flint: 5, LeatherScraps: 1 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weap', slot: 'both',
    id: 'SledgeStagbreaker',
    tier: 1,
    weight: 4, stack: 1,
    skill: SkillType.Clubs,
    damage: [
      { [DamageType.Blunt]: 20, [DamageType.Pierce]: 5 },
      { [DamageType.Blunt]: 6 }
    ],
    attacks: [{
      type: 'area',
      chain: 0,
      chainCombo: 2,
      stamina: 25,
      range: 2.4,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 15,
    parryForce: [50, 10],
    parryBonus: 2,
    knockback: 150, backstab: 2, moveSpeed: -0.2,
    recipe: {
      time: CRAFT_TIME,
      materials: { RoundLog: 20, DeerTrophy: 5, LeatherScraps: 2 },
      materialsPerLevel: { RoundLog: 5, DeerTrophy: 2, LeatherScraps: 1, BoneFragments: 10 },
      source: { station: CraftingStation.Workbench, level: 2 },
      upgrade: { station: CraftingStation.Workbench, level: 3 },
    }
  },
  { type: 'weap', slot: 'bow',
    id: 'Bow',
    tier: 1,
    weight: 1.5, stack: 1,
    skill: SkillType.Bows,
    damage: [{
      [DamageType.Pierce]: 22,
    }, {
      [DamageType.Pierce]: 3,
    }],
    attacks: [{
      type: 'proj',
      projVel: [2, 35],
      projAcc: [20, 1],
      chain: 0,
      chainCombo: 2,
      stamina: 0,
      range: 1,
    }],
    maxLvl: 4,
    durability: [50, 50],
    block: 5,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 0, backstab: 3, moveSpeed: -0.05,
    // "holdDurationMin": 2.5,
    // "holdStaminaDrain": 5,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 10, LeatherScraps: 8 },
      materialsPerLevel: { Wood: 5, LeatherScraps: 4, DeerHide: 1 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weap', slot: 'both',
    id: 'PickaxeAntler',
    tier: 2,
    toolTier: 0,
    weight: 2, stack: 1,
    skill: SkillType.Pickaxes,
    damage: [{
      [DamageType.Pierce]: 18,
      [DamageType.Pickaxe]: 18,
    }, {}],
    attacks: [{
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 10,
      range: 1.8,
    }],
    maxLvl: 1,
    durability: [100, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 10, HardAntler: 1 },
      materialsPerLevel: {},
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 0 },
    }
  },
  { type: 'weap', slot: 'secondary',
    id: 'ShieldWood',
    tier: 1,
    weight: 4, stack: 1,
    skill: SkillType.Blocking,
    damage: [{}, {}],
    attacks: [],
    maxLvl: 3,
    durability: [200, 50],
    block: [20, 5],
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 40, backstab: 4, moveSpeed: -0.2,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 10, Resin: 4, LeatherScraps: 4 },
      materialsPerLevel: { Wood: 5, Resin: 2, LeatherScraps: 2 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weap', slot: 'secondary',
    id: 'ShieldWoodTower',
    tier: 1,
    weight: 4, stack: 1,
    skill: SkillType.Blocking,
    damage: [{}, {}],
    attacks: [],
    maxLvl: 3,
    durability: [200, 50],
    block: [35, 5],
    parryForce: 0,
    parryBonus: 1,
    knockback: 40, backstab: 4, moveSpeed: -0.2,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 10, LeatherScraps: 6 },
      materialsPerLevel: { Wood: 5, LeatherScraps: 3 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
// BRONZE AGE
  { type: 'weap', slot: 'primary',
    id: 'KnifeCopper',
    tier: 2,
    weight: 0.3, stack: 1,
    skill: SkillType.Knives,
    damage: [{
      [DamageType.Slash]: 9,
      [DamageType.Pierce]: 9,
    }, {
      [DamageType.Slash]: 1,
      [DamageType.Pierce]: 1,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 1.8,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 40,
      range: 1.8,
      mul: { damage: 3, force: 4, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 8,
    parryForce: [10, 5],
    parryBonus: 4,
    knockback: 10, backstab: 10, moveSpeed: 0,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 2, Copper: 8 },
      materialsPerLevel: { GreydwarfEye: 8, Copper: 4 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'AtgeirBronze',
    tier: 2,
    weight: 2.5, stack: 1,
    skill: SkillType.Polearms,
    damage: [{
      [DamageType.Pierce]: 45,
    }, {
      [DamageType.Pierce]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 20,
      range: 3.2,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 35,
      range: 3,
      mul: { damage: 1, force: 10, stagger: 6 },
    }],
    maxLvl: 4,
    durability: [125, 50],
    block: 10,
    parryForce: [40, 5],
    parryBonus: 3,
    knockback: 30, backstab: 3, moveSpeed: -0.1,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 10, Bronze: 8, LeatherScraps: 2 },
      materialsPerLevel: { Bronze: 4 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'AxeBronze',
    tier: 2,
    toolTier: 2,
    weight: 2, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      [DamageType.Slash]: 35,
      [DamageType.Chop]: 40,
    }, {
      [DamageType.Slash]: 5,
      [DamageType.Chop]: 3,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [125, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 4, Bronze: 8, LeatherScraps: 2 },
      materialsPerLevel: { Bronze: 4, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'MaceBronze',
    tier: 2,
    weight: 2, stack: 1,
    skill: SkillType.Clubs,
    damage: [{
      [DamageType.Blunt]: 35,
    }, {
      [DamageType.Blunt]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 15,
      range: 2.4,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.5,
      mul: { damage: 2.5, force: 2, stagger: 2 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [30, 5],
    parryBonus: 2,
    knockback: 80, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 4, Bronze: 8, LeatherScraps: 3 },
      materialsPerLevel: { Bronze: 4 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'SpearBronze',
    tier: 2,
    weight: 1.5, stack: 1,
    skill: SkillType.Spears,
    damage: [{
      [DamageType.Pierce]: 35,
    }, {
      [DamageType.Pierce]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1.8,
    }, {
      type: 'proj',
      projVel: [2, 20],
      projAcc: [20, 1],
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1,
      mul: { damage: 1.5, force: 1.5, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 20, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 5, Bronze: 6, DeerHide: 2 },
      materialsPerLevel: { Wood: 3, Bronze: 4, DeerHide: 1 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'SwordBronze',
    tier: 2,
    weight: 0.8, stack: 1,
    skill: SkillType.Swords,
    damage: [{
      [DamageType.Slash]: 35,
    }, {
      [DamageType.Slash]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 2, Bronze: 8, LeatherScraps: 2 },
      materialsPerLevel: { Wood: 1, Bronze: 4, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weap', slot: 'both',
    id: 'PickaxeBronze',
    tier: 2,
    toolTier: 1,
    weight: 2, stack: 1,
    skill: SkillType.Pickaxes,
    damage: [{
      [DamageType.Pierce]: 25,
      [DamageType.Pickaxe]: 25,
    }, {
      [DamageType.Pierce]: 5,
      [DamageType.Pickaxe]: 4,
    }],
    attacks: [{
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 10,
      range: 1.8,
    }],
    maxLvl: 4,
    durability: [120, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { RoundLog: 3, Bronze: 10 },
      materialsPerLevel: { RoundLog: 1, Bronze: 5 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weap', slot: 'bow',
    id: 'BowFineWood',
    tier: 2,
    weight: 1.5, stack: 1,
    skill: SkillType.Bows,
    damage: [{
      [DamageType.Pierce]: 32,
    }, {
      [DamageType.Pierce]: 3,
    }],
    attacks: [{
      type: 'proj',
      projVel: [2, 50],
      projAcc: [20, 1],
      chain: 0,
      chainCombo: 2,
      stamina: 0,
      range: 1,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 5,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 5, backstab: 3, moveSpeed: -0.05,
    // "holdDurationMin": 2.5,
    // "holdStaminaDrain": 5,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 10, RoundLog: 10, DeerHide: 2 },
      materialsPerLevel: { FineWood: 5, RoundLog: 5, DeerHide: 2 },
      source: { station: CraftingStation.Workbench, level: 1 },
      upgrade: { station: CraftingStation.Workbench, level: 2 },
    }
  },
  { type: 'weap', slot: 'secondary',
    id: 'ShieldBronzeBuckler',
    tier: 2,
    weight: 3, stack: 1,
    skill: SkillType.Blocking,
    damage: [{}, {}],
    attacks: [],
    maxLvl: 3,
    durability: [200, 50],
    block: [45, 5],
    parryForce: 30,
    parryBonus: 2,
    knockback: 40, backstab: 4, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 4, Bronze: 10 },
      materialsPerLevel: { Wood: 1, Bronze: 5 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
// IRON AGE
  { type: 'weap', slot: 'both',
    id: 'Battleaxe',
    tier: 3,
    toolTier: 3,
    weight: 2.5, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      [DamageType.Slash]: 75,
      [DamageType.Chop]: 40,
    }, {
      [DamageType.Slash]: 6,
      [DamageType.Chop]: 2.5,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 25,
      range: 2.5,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 2.5,
      mul: { damage: 0.5, force: 2, stagger: 4 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 20,
    parryForce: [70, 5],
    parryBonus: 2,
    knockback: 70, backstab: 3, moveSpeed: -0.2,
    recipe: {
      time: CRAFT_TIME,
      materials: { AncientBark: 30, Iron: 35, LeatherScraps: 4 },
      materialsPerLevel: { AncientBark: 5, Iron: 15 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'SwordIron',
    tier: 3,
    toolTier: 0,
    weight: 0.8, stack: 1,
    skill: SkillType.Swords,
    damage: [{
      [DamageType.Slash]: 55,
    }, {
      [DamageType.Slash]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 2, Iron: 20, LeatherScraps: 3 },
      materialsPerLevel: { Wood: 1, Iron: 10, LeatherScraps: 2 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weap', slot: 'primary',
    id: 'AxeIron',
    tier: 3,
    toolTier: 3,
    weight: 2, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      [DamageType.Slash]: 55,
      [DamageType.Chop]: 50,
    }, {
      [DamageType.Slash]: 5,
      [DamageType.Chop]: 3,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [175, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 4, Iron: 20, LeatherScraps: 2 },
      materialsPerLevel: { Iron: 10, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weap', slot: 'both',
    id: 'SledgeIron',
    tier: 3,
    weight: 4, stack: 1,
    skill: SkillType.Clubs,
    damage: [{
      [DamageType.Blunt]: 55,
    }, {
      [DamageType.Blunt]: 6,
    }],
    attacks: [{
      type: 'area',
      chain: 0,
      chainCombo: 2,
      stamina: 25,
      range: 2,
      mul: { damage: 1, force: 1, stagger: 2 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 15,
    parryForce: [50, 10],
    parryBonus: 2,
    knockback: 200, backstab: 2, moveSpeed: -0.2,
    recipe: {
      time: CRAFT_TIME,
      materials: { AncientBark: 10, Iron: 30, YmirFlesh: 4, DraugrEliteTrophy: 1 },
      materialsPerLevel: { AncientBark: 2, Iron: 15, YmirFlesh: 2 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weap', slot: 'primary',
    id: 'MaceIron',
    tier: 3,
    weight: 2, stack: 1,
    skill: SkillType.Clubs,
    damage: [{
      [DamageType.Blunt]: 55,
    }, {
      [DamageType.Blunt]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 15,
      range: 2.4,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.5,
      mul: { damage: 2.5, force: 2, stagger: 2 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [30, 5],
    parryBonus: 2,
    knockback: 90, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 4, Iron: 20, LeatherScraps: 3 },
      materialsPerLevel: { Iron: 10 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weap', slot: 'primary',
    id: 'SpearElderbark',
    tier: 3,
    weight: 1.5, stack: 1,
    skill: SkillType.Spears,
    damage: [{
      [DamageType.Pierce]: 55,
    }, {
      [DamageType.Pierce]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1.8,
    }, {
      type: 'proj',
      projVel: [2, 20],
      projAcc: [20, 1],
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1,
      mul: { damage: 1.5, force: 1.5, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 20, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { AncientBark: 10, Iron: 10, TrollHide: 4 },
      materialsPerLevel: { Wood: 5, Flint: 5, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'weap', slot: 'both',
    id: 'PickaxeIron',
    tier: 3,
    toolTier: 2,
    weight: 2, stack: 1,
    skill: SkillType.Pickaxes,
    damage: [{
      [DamageType.Pierce]: 33,
      [DamageType.Pickaxe]: 33,
    }, {
      [DamageType.Pierce]: 5,
      [DamageType.Pickaxe]: 5,
    }],
    attacks: [{
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 10,
      range: 1.8,
    }],
    maxLvl: 4,
    durability: [150, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 50, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { RoundLog: 3, Iron: 20 },
      materialsPerLevel: { RoundLog: 1, Iron: 10 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weap', slot: 'both',
    id: 'AtgeirIron',
    tier: 3,
    weight: 2.5, stack: 1,
    skill: SkillType.Polearms,
    damage: [{
      [DamageType.Pierce]: 65,
    }, {
      [DamageType.Pierce]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 20,
      range: 3.2,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 35,
      range: 3,
      mul: { damage: 1, force: 10, stagger: 6 },
    }],
    maxLvl: 4,
    durability: [175, 50],
    block: 10,
    parryForce: [40, 5],
    parryBonus: 3,
    knockback: 30, backstab: 3, moveSpeed: -0.1,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 10, Iron: 30, LeatherScraps: 2 },
      materialsPerLevel: { Iron: 15, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weap', slot: 'bow',
    id: 'BowHuntsman',
    tier: 3,
    weight: 1.5, stack: 1,
    skill: SkillType.Bows,
    damage: [{
      [DamageType.Pierce]: 42,
    }, {
      [DamageType.Pierce]: 3,
    }],
    attacks: [{
      type: 'proj',
      projVel: [2, 50],
      projAcc: [20, 0],
      chain: 0,
      chainCombo: 2,
      stamina: 0,
      range: 1,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 5,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 10, backstab: 3, moveSpeed: -0.05,
    // "holdDurationMin": 2.5,
    // "holdStaminaDrain": 5,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 10, Iron: 20, Feathers: 10, DeerHide: 2 },
      materialsPerLevel: { FineWood: 5, Iron: 10, Feathers: 5, DeerHide: 2 },
      source: { station: CraftingStation.Forge, level: 1 },
      upgrade: { station: CraftingStation.Forge, level: 2 },
    }
  },
  { type: 'weap', slot: 'secondary',
    id: 'ShieldBanded',
    tier: 3,
    weight: 5, stack: 1,
    skill: SkillType.Blocking,
    damage: [
      { [DamageType.Blunt]: 10 },
      {}
    ],
    attacks: [],
    maxLvl: 3,
    durability: [200, 50],
    block: [60, 5],
    parryForce: [40, 5],
    parryBonus: 2,
    knockback: 50, backstab: 2, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 10, Iron: 8 },
      materialsPerLevel: { FineWood: 10, Iron: 4 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
  { type: 'weap', slot: 'secondary',
    id: 'ShieldIronTower',
    tier: 3,
    weight: 4, stack: 1,
    skill: SkillType.Blocking,
    damage: [{}, {}],
    attacks: [],
    maxLvl: 3,
    durability: [200, 50],
    block: [75, 5],
    parryForce: 0,
    parryBonus: 1,
    knockback: 40, backstab: 4, moveSpeed: -0.2,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 15, Iron: 10 },
      materialsPerLevel: { FineWood: 10, Iron: 5 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
// SILVER AGE
  { type: 'weap', slot: 'primary',
    id: 'SwordSilver',
    tier: 4,
    weight: 1, stack: 1,
    skill: SkillType.Swords,
    damage: [{
      [DamageType.Slash]: 75,
      [DamageType.Spirit]: 30,
    }, {
      [DamageType.Slash]: 6,
      [DamageType.Spirit]: 5,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { Wood: 2, Silver: 40, LeatherScraps: 3, Iron: 5 },
      materialsPerLevel: { Wood: 1, Silver: 20, LeatherScraps: 1, Iron: 3 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'SpearWolfFang',
    tier: 4,
    weight: 1.5, stack: 1,
    skill: SkillType.Spears,
    damage: [{
      [DamageType.Pierce]: 70,
    }, {
      [DamageType.Pierce]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1.8,
    }, {
      type: 'proj',
      projVel: [2, 20],
      projAcc: [20, 1],
      chain: 0,
      chainCombo: 2,
      stamina: 15,
      range: 1,
      mul: { damage: 1.5, force: 1.5, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 20, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { AncientBark: 10, WolfFang: 4, Silver: 2, LeatherScraps: 2 },
      materialsPerLevel: { AncientBark: 5, WolfFang: 2, Silver: 1, LeatherScraps: 1 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'weap', slot: 'primary',
    id: 'MaceSilver',
    tier: 4,
    weight: 2, stack: 1,
    skill: SkillType.Clubs,
    damage: [{
      [DamageType.Blunt]: 35,
      [DamageType.Frost]: 40,
      [DamageType.Spirit]: 20,
    }, {
      [DamageType.Frost]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      stamina: 20,
      range: 2.4,
      chainCombo: 2,
    }, {
      type: 'melee',
      chain: 0,
      stamina: 30,
      range: 2.5,
      mul: { damage: 2.5, force: 2, stagger: 2, },
      chainCombo: 2,
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [30, 5],
    parryBonus: 2,
    knockback: 120, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { AncientBark: 10, Silver: 30, YmirFlesh: 5, FreezeGland: 5 },
      materialsPerLevel: { Silver: 15 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  // TODO: SpearChitin
  { type: 'weap', slot: 'primary',
    id: 'KnifeChitin',
    tier: 4,
    weight: 0.3, stack: 1,
    skill: SkillType.Knives,
    damage: [{
      [DamageType.Slash]: 12,
      [DamageType.Pierce]: 12,
    }, {
      [DamageType.Slash]: 1,
      [DamageType.Pierce]: 1,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 1.8,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 40,
      range: 1.8,
      mul: { damage: 3, force: 4, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 10,
    parryForce: [10, 5],
    parryBonus: 4,
    knockback: 10, backstab: 10, moveSpeed: 0,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 4, Chitin: 20, LeatherScraps: 2 },
      materialsPerLevel: { Chitin: 10 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
  { type: 'weap', slot: 'bow',
    id: 'BowDraugrFang',
    tier: 4,
    weight: 1.5, stack: 1,
    skill: SkillType.Bows,
    damage: [{
      [DamageType.Pierce]: 47,
      [DamageType.Poison]: 5,
    }, {
      [DamageType.Pierce]: 3,
      [DamageType.Poison]: 5,
    }],
    attacks: [{
      type: 'proj',
      projVel: [2, 60],
      projAcc: [20, 0],
      chain: 0,
      chainCombo: 2,
      stamina: 0,
      range: 1,
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 5,
    parryForce: 0,
    parryBonus: 1.5,
    knockback: 10, backstab: 3, moveSpeed: -0.05,
    // "holdDurationMin": 2.5,
    // "holdStaminaDrain": 5,
    recipe: {
      time: CRAFT_TIME,
      materials: { AncientBark: 10, Silver: 20, DeerHide: 2, Guck: 10, },
      materialsPerLevel: { AncientBark: 5, Silver: 10, DeerHide: 2, Guck: 2 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    }
  },
  { type: 'weap', slot: 'secondary',
    id: 'ShieldSilver',
    tier: 4,
    weight: 5, stack: 1,
    skill: SkillType.Blocking,
    damage: [{
      [DamageType.Blunt]: 10,
    }, {}],
    attacks: [],
    maxLvl: 3,
    durability: [200, 50],
    block: [75, 5],
    parryForce: [40, 5],
    parryBonus: 1.5,
    knockback: 50, backstab: 4, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 10, Silver: 8 },
      materialsPerLevel: { FineWood: 10, Silver: 4 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'weap', slot: 'secondary',
    id: 'ShieldSerpentscale',
    tier: 4,
    weight: 5, stack: 1,
    skill: SkillType.Blocking,
    damage: [{
      [DamageType.Blunt]: 10,
    }, {
    }],
    attacks: [],
    maxLvl: 3,
    durability: [250, 50],
    block: [90, 5],
    parryForce: [50, 5],
    parryBonus: 1,
    knockback: 50, backstab: 4, moveSpeed: -0.1,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 10, Iron: 4, SerpentScale: 8 },
      materialsPerLevel: { FineWood: 10, Iron: 2, SerpentScale: 4 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
// BLACK AGE
  { type: 'weap', slot: 'both',
    id: 'AtgeirBlackmetal',
    tier: 5,
    weight: 2.5, stack: 1,
    skill: SkillType.Polearms,
    damage: [{
      [DamageType.Pierce]: 105,
    }, {
      [DamageType.Pierce]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 20,
      range: 3.2,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 35,
      range: 3,
      mul: { damage: 1, force: 10, stagger: 6 },
    }],
    maxLvl: 4,
    durability: [175, 50],
    block: 10,
    parryForce: [40, 5],
    parryBonus: 3,
    knockback: 30, backstab: 3, moveSpeed: -0.1,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 10, BlackMetal: 30, LinenThread: 5 },
      materialsPerLevel: { BlackMetal: 15, LinenThread: 5 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'weap', slot: 'primary',
    id: 'AxeBlackMetal',
    tier: 5,
    toolTier: 4,
    weight: 2, stack: 1,
    skill: SkillType.Axes,
    damage: [{
      [DamageType.Slash]: 95,
      [DamageType.Chop]: 60,
    }, {
      [DamageType.Slash]: 5,
      [DamageType.Chop]: 3,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.2,
    }],
    maxLvl: 4,
    durability: [175, 50],
    block: 20,
    parryForce: 0,
    parryBonus: 2,
    knockback: 60, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 6, BlackMetal: 20, LinenThread: 5 },
      materialsPerLevel: { BlackMetal: 10, LinenThread: 5 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'weap', slot: 'primary',
    id: 'KnifeBlackMetal',
    tier: 5,
    weight: 0.3, stack: 1,
    skill: SkillType.Knives,
    damage: [{
      [DamageType.Slash]: 18,
      [DamageType.Pierce]: 18,
    }, {
      [DamageType.Slash]: 1,
      [DamageType.Pierce]: 1,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 5,
      range: 1.8,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 40,
      range: 1.8,
      mul: { damage: 3, force: 4, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [100, 50],
    block: 15,
    parryForce: [10, 5],
    parryBonus: 4,
    knockback: 10, backstab: 10, moveSpeed: 0,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 4, BlackMetal: 10, LinenThread: 5 },
      materialsPerLevel: { BlackMetal: 4, LinenThread: 5 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'weap', slot: 'primary',
    id: 'SwordBlackmetal',
    tier: 5,
    weight: 0.8, stack: 1,
    skill: SkillType.Swords,
    damage: [{
      [DamageType.Slash]: 95,
    }, {
      [DamageType.Slash]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 2, BlackMetal: 20, LinenThread: 5 },
      materialsPerLevel: { BlackMetal: 10, LinenThread: 5 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'weap', slot: 'primary',
    id: 'MaceNeedle',
    tier: 5,
    weight: 2, stack: 1,
    skill: SkillType.Clubs,
    damage: [{
      [DamageType.Blunt]: 50,
      [DamageType.Pierce]: 45,
    }, {
      [DamageType.Pierce]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 15,
      range: 2.4,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 2,
      stamina: 30,
      range: 2.5,
      mul: { damage: 2.5, force: 2, stagger: 2 },
    }],
    maxLvl: 4,
    durability: [150, 50],
    block: 20,
    parryForce: [30, 5],
    parryBonus: 2,
    knockback: 90, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 5, Iron: 20, Needle: 5, LinenThread: 10 },
      materialsPerLevel: { Iron: 2, LinenThread: 2 },
      source: { station: CraftingStation.Forge, level: 4 },
      upgrade: { station: CraftingStation.Forge, level: 5 },
    },
  },
  { type: 'weap', slot: 'secondary',
    id: 'ShieldBlackmetal',
    tier: 5,
    weight: 5, stack: 1,
    skill: SkillType.Blocking,
    damage: [{
      [DamageType.Blunt]: 10,
    }, {}],
    attacks: [],
    maxLvl: 3,
    durability: [200, 50],
    block: [90, 5],
    parryForce: [50, 5],
    parryBonus: 1.5,
    knockback: 50, backstab: 4, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 10, BlackMetal: 8, Chain: 5 },
      materialsPerLevel: { FineWood: 10, BlackMetal: 4, Chain: 2 },
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
  { type: 'weap', slot: 'secondary',
    id: 'ShieldBlackmetalTower',
    tier: 5,
    weight: 5, stack: 1,
    skill: SkillType.Blocking,
    damage: [{
      [DamageType.Blunt]: 10,
    }, {
    }],
    attacks: [],
    maxLvl: 3,
    durability: [200, 50],
    block: [105, 5],
    parryForce: [0, 5],
    parryBonus: 1,
    knockback: 50, backstab: 4, moveSpeed: -0.2,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 15, BlackMetal: 10, Chain: 7 },
      materialsPerLevel: { FineWood: 15, BlackMetal: 6, Chain: 3 },  
      source: { station: CraftingStation.Forge, level: 3 },
      upgrade: { station: CraftingStation.Forge, level: 4 },
    }
  },
// FLAME AGE
  { type: 'weap', slot: 'primary',
    id: 'SwordIronFire',
    tier: 6,
    toolTier: 0,
    weight: 1, stack: 1,
    skill: SkillType.Swords,
    damage: [{
      [DamageType.Slash]: 55,
      [DamageType.Fire]: 30,
    }, {
      [DamageType.Slash]: 5,
      [DamageType.Fire]: 6,
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 0,
      stamina: 30,
      range: 2.4,
      mul: { damage: 3, force: 1, stagger: 1 },
    }],
    maxLvl: 4,
    durability: [200, 50],
    block: 10,
    parryForce: [20, 5],
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
    recipe: {
      time: CRAFT_TIME,
      materials: { FineWood: 2, Flametal: 20, SurtlingCore: 20, LeatherScraps: 3 },
      materialsPerLevel: { Flametal: 10, SurtlingCore: 10, LeatherScraps: 2 },
      source: { station: CraftingStation.Forge, level: 2 },
      upgrade: { station: CraftingStation.Forge, level: 3 },
    },
  },
  { type: 'weap', slot: 'primary',
    id: 'SwordCheat',
    tier: 999,
    toolTier: 10,
    weight: 1, stack: 1,
    skill: SkillType.Swords,
    damage: [{
      [DamageType.Slash]: 10000,
      [DamageType.Chop]: 10000,
      [DamageType.Pickaxe]: 10000,
    }, {
    }],
    attacks: [{
      type: 'melee',
      chain: 3,
      chainCombo: 2,
      stamina: 10,
      range: 2.4,
    }, {
      type: 'melee',
      chain: 0,
      chainCombo: 0,
      stamina: 30,
      range: 2.4,
    }],
    maxLvl: 1,
    durability: [100, 50],
    block: 10,
    parryForce: 0,
    parryBonus: 2,
    knockback: 40, backstab: 3, moveSpeed: -0.05,
  },
];
