/** @type {Record<string, string>} */
const langMapping = {
    'en': 'English',
    'sv': 'Swedish',
    'fr': 'French',
    'it': 'Italian',
    'de': 'German',
    'es': 'Spanish',
    'ru': 'Russian',
    'ro': 'Romanian',
    'bg': 'Bulgarian',
    'mk': 'Macedonian',
    'fi': 'Finnish',
    'da': 'Danish',
    'no': 'Norwegian',
    'is': 'Icelandic',
    'tr': 'Turkish',
    'lt': 'Lithuanian',
    'cs': 'Czech',
    'hu': 'Hungarian',
    'sk': 'Slovak',
    'pl': 'Polish',
    'nl': 'Dutch',
    'pt-PT': 'Portuguese_European',
    'pt-BR': 'Portuguese_Brazilian',
    'zh-CN': 'Chinese',
    'ja': 'Japanese',
    'ko': 'Korean',
    'hi': 'Hindi',
    'th': 'Thai',
    'hr': 'Croatian',
    'ka': 'Georgian',
    'el': 'Greek',
    'sr': 'Serbian',
    'uk': 'Ukrainian',
};

exports.langMapping = langMapping;
